canyongbs/aidingapp

resources/views/filament/footer.blade.php
- https://canyongbs.atlassian.net/browse/ADVAPP-10
Updates the copyright footer in application.
>
=> [AIDAPP-10]: Update in-product copyright statement.

app-modules/assistant/src/Filament/Pages/PersonalAssistant.php
- https://canyongbs.atlassian.net/browse/AIDAPP-11
> Update nav labels
> No
=> [AIDAPP-11]: Optimize presentation of Support Assistant and Contacts navigation labels

app-modules/portal/routes/api.php, app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalLogoutController.php, portals/knowledge-management/src/Components/MobileSidebar.vue, portals/knowledge-management/src/Components/SidebarContent.vue
- https://canyongbs.atlassian.net/browse/AIDAPP-25
> This PR adds logout capabilities to the Knowledge Management Portal
> No
=> [AIDAPP-25]: Add logout capability to Knowledge Management Portal

docs/local-setup.md
- https://canyongbs.atlassian.net/browse/ADVAPP-438
Updates the local setup docs.
>
=> [ADVAPP-438] Add more local setup details

.dockerignore
- N/A
Fixes deployment issue by updating the `devops` submodule. Also adds some additional files to Docker ignore.
>
=> [Bugfix] Update devops submodule

.github/workflows/release.yml, docker/s6-overlay/s6-rc.d/nginx/data/check
- https://canyongbs.atlassian.net/browse/AIDAPP-30
Sets up CI/CD deployment for AidingApp Prod. Before merging in https://github.com/canyongbs/devops/pull/9 should be merged and this branches submodule pointed back to `main` on `devops`.
>
=> [AIDAPP-30]: Setup CI/CD for production

app-modules/authorization/src/Console/Commands/SetupPermissions.php, app-modules/authorization/src/Console/Commands/SetupRoleGroups.php, app-modules/authorization/src/Console/Commands/SetupRoles.php, app-modules/authorization/src/Console/Commands/SyncRolesAndPermissions.php, app-modules/engagement/src/Console/Commands/DeliverEngagements.php, app-modules/notification/src/Console/Commands/SimulatedNotification.php, app/Console/Commands/ClearTestMigrationCache.php, app/Console/Commands/CreateSuperAdmin.php, app/Console/Commands/CreateTenant.php, app/Console/Commands/CreateTenantCommand.php, app/Console/Commands/GenerateHelperFiles.php, app/Console/Commands/GenerateLandlordApiKey.php, app/Console/Commands/MigrateFreshLandlord.php, app/Console/Commands/MigrateLandlord.php, app/Console/Commands/OpenSearchDeleteAllIndices.php, app/Console/Commands/OpenSearchList.php, app/Console/Commands/PrintApiSchema.php, app/Console/Commands/ValidateGraphQL.php
- https://canyongbs.atlassian.net/browse/ADVAPP-353
=> [ADVAPP-353]: Ensure all commands return static::SUCCESS or static::FAILURE

composer.lock
- https://canyongbs.atlassian.net/browse/AIDAPP-41
>
>
=> [AIDAPP-41]: Enhance navigation look and feel in Aiding App

README.md
- https://canyongbs.atlassian.net/browse/AIDAPP-3
>
Update to readme file to include feature details about the Aiding App project.
>
N/A
=> AIDAPP-3: Update readme file for the project

app-modules/assistant/src/Filament/Pages/SupportAssistant.php, app-modules/contact/src/Filament/Resources/ContactResource.php, app-modules/in-app-communication/src/Filament/Pages/UserChat.php, app-modules/inventory-management/src/Filament/Resources/AssetResource.php, app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource.php, app-modules/portal/src/Filament/Pages/ManagePortalSettings.php, app-modules/service-management/src/Filament/Resources/ChangeRequestResource.php, app-modules/service-management/src/Filament/Resources/ServiceRequestResource.php, app-modules/task/src/Filament/Resources/TaskResource.php, app/Filament/Pages/ManageLicenseSettings.php
- https://canyongbs.atlassian.net/browse/AIDAPP-42
>
Renamed and reordered menu items.
>
=> [AIDAPP-42]: Reorder main navigation

app-modules/consent/database/seeders/ConsentAgreementSeeder.php, app-modules/division/database/factories/DivisionFactory.php, app-modules/knowledge-base/database/seeders/KnowledgeBaseCategorySeeder.php, app-modules/service-management/database/seeders/ServiceRequestTypeSeeder.php
n/a
> Removes our reliance on dev dependency when seeding a new tenant.
> No
=> [Hotfix] Remove reliance on Faker when seeding new Tenant

app-modules/authorization/src/Enums/LicenseType.php
- https://canyongbs.atlassian.net/browse/AIDAPP-39
>
Updated the license type labels.
>
=> [AIDAPP-39]: Enhance Presentation of License Management

.gitignore
- https://canyongbs.atlassian.net/browse/AIDAPP-43
Updates the devops submodule to pull in changes tagging ASM records to the specific version number.
>
=> [AIDAPP-43]: Apply labels to ASM and set in task definitions

app/Exceptions/Handler.php, composer.json, composer.lock, config/sentry.php
- https://canyongbs.atlassian.net/browse/AIDAPP-33
>
>
=> [AIDAPP-33]

docs/data-migrations.md
Seems like the rest of the cleanup had already happened before I got there, so I just transferred over the docs.
=> [AIDAPP-37]: Remove any details on one time operations and set up new migration paradigm

composer.lock
- https://canyongbs.atlassian.net/browse/ADVAPP-504
=> [ADVAPP-504]: Fix navigation auto-scroll when sub navigation present

app-modules/service-management/database/seeders/ServiceRequestStatusSeeder.php, app-modules/service-management/src/Enums/SystemServiceRequestClassification.php
- https://canyongbs.atlassian.net/browse/AIDAPP-51
> Update default statuses under Service Request Statuses. Added new classification "Waiting". Removed the Pending College and Pending District.  Renamed "Pending Student" to "Pending for Customer".
=> [AIDAPP-51] Update default statuses

app-modules/service-management/src/Enums/SystemServiceRequestClassification.php, app/Filament/Pages/Dashboard.php, app/Filament/Widgets/ListServiceRequestTableWidgets.php, app/Filament/Widgets/ServiceRequestDonutChart.php, app/Filament/Widgets/ServiceRequestLineChart.php, app/Filament/Widgets/ServiceRequestWidget.php
- https://canyongbs.atlassian.net/browse/AIDAPP-49
> Re-update the Home section and added service requests stats, charts.
=> [AIDAPP-49] Enhance home screen for service management

config/database.php
https://canyongbs.atlassian.net/browse/ADVAPP-508
> Applying same fix to AidingApp as was applied to AdvisingApp so the session driver can be Redis.
> No
=> [ADVAPP-508]: Session Driver inconsistencies

app-modules/service-management/database/migrations/2023_08_11_235451_create_implicit_varchar_as_uuid_cast.php
- https://canyongbs.atlassian.net/browse/AIDAPP-58
> Unable to search in service requests module due to some casting issue of column which fixed by implicit migration.
=> [AIDAPP-58] Unable to search service requests

resources/views/vendor/mail/html/message.blade.php
- https://canyongbs.atlassian.net/browse/AIDAPP-62
> Updated the new copyright template for emails.
=> [AIDAPP-62] Update email copyright template

app-modules/portal/routes/api.php, app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/GetServiceRequestsController.php, app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalCategoryController.php, app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalController.php, portals/knowledge-management/src/App.vue
- https://canyongbs.atlassian.net/browse/AIDAPP-22
>
Split Knowledge Management portal render / load functionality.
>
=> [AIDAPP-22]: Split Knowledge Management Portal Render / Load Functionality

app-modules/inventory-management/src/Policies/AssetLocationPolicy.php, app-modules/inventory-management/src/Policies/AssetPolicy.php, app-modules/inventory-management/src/Policies/AssetStatusPolicy.php, app-modules/inventory-management/src/Policies/AssetTypePolicy.php, app/DataTransferObjects/LicenseManagement/LicenseAddonsData.php, app/Enums/Feature.php, app/Filament/Pages/ManageLicenseSettings.php
- https://canyongbs.atlassian.net/browse/AIDAPP-54
> Asset Management is now under Add-ons in global settings which will be visible based on toggle is on or off.
=> [AIDAPP-54] Enhance the way Asset Management works

app/Multitenancy/Http/Middleware/NeedsTenant.php, app/Providers/Filament/AdminPanelProvider.php, app/Providers/Filament/LandlordPanelProvider.php, app/Providers/RouteServiceProvider.php, docker/s6-overlay/s6-rc.d/nginx/data/check, resources/views/errors/404.blade.php
- https://canyongbs.atlassian.net/browse/AIDAPP-63
Resolve the error throwing up the tenant resolution issue and add a new ping URL.
>
=> [AIDAPP-63]: Resolve tenant resolution error throwing when app is access with unknown URL

app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/CreateServiceRequestType.php, app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/EditServiceRequestType.php, app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/ViewServiceRequestType.php, app/DataTransferObjects/LicenseManagement/LicenseAddonsData.php, app/Enums/Feature.php, app/Filament/Pages/ManageLicenseSettings.php
- https://canyongbs.atlassian.net/browse/AIDAPP-75
Added a `Feedback Management` addon toggle and related checks.
=> [AIDAPP-75]: Enhance the way Feedback Collection works in the application

app/Models/Scopes/SetupIsComplete.php, app/Observers/TenantObserver.php, database/landlord/2024_04_09_154843_data_fill_setup_complete_on_tenants_table.php, database/landlord/2024_04_09_155810_data_activate_setup_complete_feature.php, database/landlord/2024_04_19_235223_data_purge_setup_complete_feature.php
- https://canyongbs.atlassian.net/browse/AIDAPP-46
>
Cleaned up the `setup-complete` feature flag.
>
=> [AIDAPP-46]: Clean up setup-complete feature flag

resources/css/filament/admin/theme.css
- https://canyongbs.atlassian.net/browse/AIDAPP-67
Adjusted the menu styles.
=> [AIDAPP-67]: Enhance look and feel of navigation in Aiding App

app-modules/authorization/src/Filament/Resources/PermissionResource.php, app-modules/authorization/src/Filament/Resources/RoleResource.php, app-modules/division/src/Filament/Resources/DivisionResource.php, app-modules/team/src/Filament/Resources/TeamResource.php, app/Filament/Clusters/ArtificialIntelligence.php, app/Filament/Clusters/ContactManagement.php, app/Filament/Clusters/GlobalSettings.php, app/Filament/Clusters/ProductIntegrations.php, app/Filament/Clusters/UserManagement.php, app/Filament/Resources/SystemUserResource.php, app/Filament/Resources/UserResource.php, app/Filament/Resources/UserResource/Pages/ListUsers.php, app/Providers/Filament/AdminPanelProvider.php
- https://canyongbs.atlassian.net/browse/AIDAPP-73
> Update The Navigation Experience for Users and Permissions
=> [AIDAPP-73] Update Navigation Experience for Users and Permissions

app-modules/contact/src/Filament/Resources/ContactResource.php, app-modules/contact/src/Filament/Resources/ContactResource/Pages/AssetManagement.php, app-modules/contact/src/Filament/Resources/ContactResource/Pages/ContactServiceManagement.php
- https://canyongbs.atlassian.net/browse/AIDAPP-80
> Enhance the way contact records work in the application. Asset Management in student profile is now separate from Service Requests. Service Management in student is now renamed to Service Requests as it's display on Service requests from now.
=> [AIDAPP-80] Enhance the way contact records work in the application

app-modules/portal/database/migrations/2024_05_21_144403_data_remove_from_portal_settings.php, app-modules/portal/src/Filament/Pages/ManagePortalSettings.php, app-modules/portal/src/Settings/PortalSettings.php
- https://canyongbs.atlassian.net/browse/AIDAPP-81
> Remove CRM and Branding Settings from Portal section
=> [AIDAPP-81] Remove CRM and Branding Settings from Portal section

app-modules/service-management/src/Enums/SystemChangeRequestClassification.php, app-modules/service-management/src/Enums/SystemServiceRequestClassification.php, app-modules/service-management/src/Models/Concerns/ClassificationInterface.php, app-modules/service-management/src/Models/Scopes/ClassifiedIn.php, app/Filament/Widgets/ServiceRequestDonutChart.php, app/Filament/Widgets/ServiceRequestLineChart.php, app/Filament/Widgets/ServiceRequestWidget.php
- https://canyongbs.atlassian.net/browse/AIDAPP-90
> Added more status (except closed) for open service requests count in widget. Fix height issue in Line chart, Donut chart and they have now equal height.
______________________________________________
=> [AIDAPP-90] Review Open Service Requests query logic for dashboard

.env.example, app-modules/form/src/Actions/GenerateFormKitSchema.php, app-modules/form/src/Actions/GenerateSubmissibleValidation.php, app-modules/form/src/Filament/Blocks/SelectFormFieldBlock.php, app-modules/form/src/Models/Submissible.php, app-modules/knowledge-base/database/seeders/KnowledgeBaseItemSeeder.php, app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/CreateServiceRequestController.php, app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalRequestAuthenticationController.php, app-modules/service-management/src/Models/ServiceRequestFormStep.php, config/local_development.php, database/seeders/LocalDevelopmentSeeder.php, portals/knowledge-management/src/App.vue, portals/knowledge-management/src/Components/DesktopSidebar.vue, portals/knowledge-management/src/Pages/CreateServiceRequest.vue, portals/knowledge-management/src/Pages/Home.vue, portals/knowledge-management/src/Pages/SelectServiceRequestType.vue, portals/knowledge-management/src/portal.css, resources/views/test-embed.blade.php, widgets/service-request-form/src/FormKit/theme.js
- https://canyongbs.atlassian.net/browse/AIDAPP-88
Makes all portal service requests forms multistep with a default first step containing required preset fields.
This does not include the file upload field as that will be covered in a subsequent pr.
=> [AIDAPP-88]: Enhance the experience for all service requests

app-modules/service-management/src/Models/ServiceRequestHistory.php
- https://canyongbs.atlassian.net/browse/AIDAPP-96
Fixes bug that throws exception in the ServiceRequest timeline view when previous values were `null`.
>
=> [AIDAPP-96]: Timeline is throwing an error in a service request

app-modules/knowledge-base/src/Jobs/KnowledgeBaseItemDownloadExternalMedia.php
- https://canyongbs.atlassian.net/browse/AIDAPP-82
Sets the name of the temp file properly to prevent issues when converting external media.
>
=> [AIDAPP-82]: Resolve KB image issues

app-modules/contact/src/Filament/Resources/ContactResource/RelationManagers/EngagementsRelationManager.php, app-modules/engagement/src/Notifications/EngagementEmailNotification.php, app-modules/engagement/src/Notifications/EngagementFailedNotification.php, app-modules/engagement/src/Notifications/EngagementSmsNotification.php, app-modules/notification/src/Notifications/BaseNotification.php
- https://canyongbs.atlassian.net/browse/AIDAPP-95
> Fixes issue with engagements attempting to send indefinitely.
> No
=> [AIDAPP-95]: Failed Engagements attempt to resend indefinitely

database/seeders/NewTenantSeeder.php
- https://canyongbs.atlassian.net/browse/AIDAPP-97
> Removes the setup roles process from the new tenant seeder, explicitly seeds the `authorization.super_admin` role.
> No
=> [AIDAPP-97]: Eliminate all currently seeded roles

resources/views/vendor/cookie-consent/dialog.blade.php
- https://canyongbs.atlassian.net/browse/AIDAPP-109
Fixed cookie consent z-index.
=> [AIDAPP-109]: Fix display issue for cookies banner

app-modules/portal/database/migrations/2024_05_31_025823_create_portal_logo_settings.php, app-modules/portal/database/migrations/2024_05_31_144403_create_feature_flag_for_portal_logo.php, app-modules/portal/src/Filament/Pages/ManagePortalSettings.php
- https://canyongbs.atlassian.net/browse/AIDAPP-108
> In portal section add an media field to upload header logo.
> Create migration for field and also doe pennant/feature.
=> Create header logo in portal page

app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalController.php, portals/knowledge-management/src/App.vue, portals/knowledge-management/src/Components/Header.vue, portals/knowledge-management/src/Components/SidebarContent.vue
- https://canyongbs.atlassian.net/browse/AIDAPP-108
> Create vue component to create a header for portal frontend page. Also add logo and sign in button in the header.
=> Create header on portal page - frontend

app/Support/MediaEncoding/TiptapMediaEncoder.php
- https://canyongbs.atlassian.net/browse/AIDAPP-123
Fixes a bug with existing media processing and encoding.
>
=> [AIDAPP-123]: Knowledgebase existing media saving bug

app/Support/MediaEncoding/TiptapMediaEncoder.php
- https://canyongbs.atlassian.net/browse/AIDAPP-123
Fix AIDAPP-123 part two, regex strikes back.
>
=> [AIDAPP-123]: Better match the path the check for file existence

app-modules/notification/src/Notifications/Messages/MailMessage.php, database/migrations/2024_06_07_122245_data_deactivate_notification_settings_from_name_column.php
- https://canyongbs.atlassian.net/browse/AIDAPP-112
> Cleanup for notification-settings-from-name feature flag
=> [AIDAPP-112]: [Cleanup] notification-settings-from-name feature flag

app-modules/portal/src/Filament/Pages/ManagePortalSettings.php
- https://canyongbs.atlassian.net/browse/AIDAPP-119
> Change Portals to Client Portal and Change Knowledge Portal to Client Portal.
=> [AIDAPP-119]: Update labels in global settings for Portals and Knowledge Portal

app-modules/portal/database/migrations/2024_06_11_093620_delete_portal_footer_records_from_settings_table.php, app-modules/portal/src/Filament/Pages/ManagePortalSettings.php, app-modules/portal/src/Settings/PortalSettings.php
…Portal
- https://canyongbs.atlassian.net/browse/AIDAPP-120
> Remove footer-related code from settings files and also make migration for it.
=> [AIDAPP-120]: Remove footer placeholder block in the Global Settings > Portal configuration

app-modules/knowledge-base/src/Models/KnowledgeBaseItem.php, app-modules/knowledge-base/src/Observers/KnowledgeBaseItemObserver.php, app/Support/MediaEncoding/TiptapMediaEncoder.php, database/migrations/2024_06_12_201706_data_fix_kb_article_media_collection_names.php
- N/A
Fixes issues with the editor images not being properly handled.
>
=> [BUGFIX]: KB editor images fix

app/Listeners/ClearSentryUser.php, app/Listeners/SetSentryUser.php, app/Multitenancy/Listeners/RemoveSentryTenantTag.php, app/Multitenancy/Listeners/SetSentryTenantTag.php, app/Providers/AppServiceProvider.php, app/Providers/EventServiceProvider.php, config/octane.php
- https://canyongbs.atlassian.net/browse/AIDAPP-124
Adds the Tenant ID and User ID to the Sentry context.
>
=> [AIDAPP-124]: Populate Tenant ID and User ID into Sentry reports

app-modules/contact/src/Filament/Resources/OrganizationResource/Pages/CreateOrganization.php, app-modules/contact/src/Filament/Resources/OrganizationResource/Pages/EditOrganization.php, app-modules/contact/tests/Organization/RequestFactories/CreateOrganizationRequestFactory.php, app-modules/contact/tests/Organization/RequestFactories/EditOrganizationRequestFactory.php, database/migrations/2024_06_13_100154_data_seed_data_in_organization_types_table.php, database/migrations/2024_06_13_100226_data_seed_data_in_organization_industries_table.php, database/seeders/NewTenantSeeder.php
- https://canyongbs.atlassian.net/browse/AIDAPP-132
> Changes done as asked in task description.
>
=> [AIDAPP-132]: Additional Organization improvements

app/Console/Commands/CreatePermissionMigration.php, app/Overrides/Laravel/PermissionMigrationCreator.php, app/Providers/AppServiceProvider.php, database/migrations/Concerns/CanModifyPermissions.php, docs/data-migrations.md, docs/roles-and-permissions.md, stubs/permission-migration.stub
- N/A
Brings over permission migration details that were set in AdvisingApp.
>
=> [AIDAPP-86]: Copy over permission migration creation details from ADVAPP

app-modules/portal/database/migrations/2024_06_14_115614_data_add_favicon_in_settings_table.php, app-modules/portal/src/Filament/Pages/ManagePortalSettings.php, app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalController.php, app-modules/portal/src/Settings/PortalSettings.php, app/Models/SettingsProperty.php, portals/knowledge-management/src/App.vue
…portal
- https://canyongbs.atlassian.net/browse/AIDAPP-129
> please check with hard refresh or in private window.
>
=> [AIDAPP-129]: Introduce the ability to upload a favicon image to the portal

app-modules/portal/resources/views/livewire/render-knowledge-management-portal.blade.php, portals/knowledge-management/src/App.vue
- https://canyongbs.atlassian.net/browse/AIDAPP-126
>please test with hard refresh or in private window.
>
=> [AIDAPP-126]: Improve the boxed portal view to be more prominent

portals/knowledge-management/src/Components/Header.vue
- https://canyongbs.atlassian.net/browse/AIDAPP-127
> Fix the scaling issue for portal header logo in mobile view
=> [AIDAPP- 127] - Address scaling to mobile view for the logo scaling

portals/knowledge-management/src/Components/Header.vue
- https://canyongbs.atlassian.net/browse/AIDAPP-128
> Change portal header background colour and sign in button colour.
=> [AIDAPP-128]: Improve the portal display background and sign in button

Dockerfile, app/Console/Commands/BuildAssets.php, docker-compose.dev.yml, docker/s6-overlay/s6-rc.d/build-assets/dependencies, docker/s6-overlay/s6-rc.d/build-assets/type, docker/s6-overlay/s6-rc.d/build-assets/up, docker/s6-overlay/s6-rc.d/laravel-octane/dependencies, docker/s6-overlay/scripts/build-assets
- https://canyongbs.atlassian.net/browse/AIDAPP-105
Adds asset rebuild to the startup processes of the application.
>
=> [AIDAPP-105]: Add s6-overlay build scripts to build assets on container startup

app-modules/form/src/Actions/GenerateSubmissibleEmbedCode.php, app-modules/portal/src/Actions/GeneratePortalEmbedCode.php, app/Providers/AppServiceProvider.php
- N/A
Merges the hotfixes that have gone out in `0.15.2` into `main`
>
=> [Hotfix]: 0.15.2

app-modules/engagement/src/Actions/EngagementEmailChannelDelivery.php, app-modules/engagement/src/Actions/EngagementSmsChannelDelivery.php
- https://canyongbs.atlassian.net/browse/AIDAPP-143
See https://github.com/canyongbs/advisingapp/pull/843 for a detailed explanation of this change.
>
=> [AIDAPP-143]: Prevent Engagements from putting jobs onto the email queue if it's on the queue but hasn't been processed

app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/EditKnowledgeBaseItem.php
- https://canyongbs.atlassian.net/browse/AIDAPP-147
> Reduce confusion around accessing KB article properties
> 
=> [AIDAPP-147]: Reduce confusion around accessing KB article properties

app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource.php
…n navigation
- https://canyongbs.atlassian.net/browse/AIDAPP-153
>label changed. 
>
=> [AIDAPP-153] Rename Knowledge Base to Knowledge Management in the main navigation

app-modules/contact/src/Filament/Resources/ContactResource.php, app-modules/contact/src/Filament/Resources/OrganizationResource.php, app-modules/in-app-communication/src/Filament/Pages/UserChat.php, app-modules/inventory-management/src/Filament/Resources/AssetResource.php, app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource.php, app-modules/service-management/src/Filament/Resources/ChangeRequestResource.php, app-modules/service-management/src/Filament/Resources/ServiceRequestResource.php, app-modules/task/src/Filament/Resources/TaskResource.php, app/Filament/Clusters/UsageAuditing.php, app/Filament/Pages/ProductHealth.php, app/Filament/Pages/ReportLibrary.php, app/Providers/Filament/AdminPanelProvider.php
- https://canyongbs.atlassian.net/browse/AIDAPP-152
> Done as per requirements.
>
=> [AIDAPP-152]: Reorganize the primary navigation user experience

app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/ListKnowledgeBaseItems.php, app/Support/MediaEncoding/TiptapMediaEncoder.php
- https://canyongbs.atlassian.net/browse/AIDAPP-125
> Add cloning feature for knowledge base articles.
=> [AIDAPP-125]: Introduce ability to duplicate knowledge base articles

app-modules/portal/src/Filament/Pages/ManagePortalSettings.php
- https://canyongbs.atlassian.net/browse/AIDAPP-149
> Enhance Client Portal UI settings for Logo and Favicon
=> [AIDAPP-149]: Enhance Client Portal UI settings for Logo and Favicon

app-modules/contact/src/Filament/Resources/ContactResource/RelationManagers/ServiceRequestsRelationManager.php, app-modules/service-management/database/migrations/2024_06_25_223932_data_soft_delete_service_request_priorties_with_a_deleted_type.php, app-modules/service-management/src/Observers/ServiceRequestTypeObserver.php, app-modules/service-management/src/Providers/ServiceManagementServiceProvider.php, app-modules/service-management/tests/ServiceRequestType/ServiceRequestTypeObserverTest.php
- https://canyongbs.atlassian.net/browse/AIDAPP-155
Fixes issues caused by deleted `ServiceRequestType`s. And now cascades the soft deleting of a `ServiceRequestType` to it's related `ServiceRequestPriority`s.
>
=> [AIDAPP-155]: Investigate and resolve cause of error related to service management issue

resources/views/vendor/filament-spatie-health/pages/health-check-results.blade.php
- https://canyongbs.atlassian.net/browse/AIDAPP-168
Copy of https://github.com/canyongbs/advisingapp/pull/862.
Temporary override to fix function redeclaration error in vendor package.
PR opened here: https://github.com/shuvroroy/filament-spatie-laravel-health/pull/51
=> [AIDAPP-168]: The health check page is throwing 500s randomly when viewed in Dev and Prod

app-modules/contact/database/migrations/2024_07_01_135950_add_organization_id_column_into_contacts_table.php, app-modules/contact/src/Filament/Resources/OrganizationResource.php, app-modules/contact/src/Filament/Resources/OrganizationResource/Pages/EditOrganization.php, app-modules/contact/src/Filament/Resources/OrganizationResource/Pages/ManageContacts.php, app-modules/contact/src/Filament/Resources/OrganizationResource/Pages/ViewOrganization.php, app-modules/contact/src/Filament/Resources/OrganizationResource/RelationManagers/ContactsRelationManager.php, app-modules/contact/src/Models/Contact.php, app-modules/contact/src/Models/Organization.php
- https://canyongbs.atlassian.net/browse/AIDAPP-170
> Create relationship between Organization and Contact
> Change Organization Resource pages to work like above.
> Relation manager should have an Attach action to add a contact to the Organization
=> [AIDAPP-170]: Enhance organizations to relate to contacts

.github/pull_request_template.md
- https://canyongbs.atlassian.net/browse/AIDAPP-142
This updates the repository PR template to update details in each section and adds a section to list added Feature Flags.
N/A
No
=> [AIDAPP-142]: Update PR template to ask whether or not a Feature Flag was added in the PR

composer.json, composer.lock, config/queue.php
- https://canyongbs.atlassian.net/browse/AIDAPP-158
> Implement the SQS feature configuration in AIDING App.
=> [AIDAPP-158] Implement Laravel SQS Extended

database/migrations/2024_07_10_085735_data_update_value_of_time_to_resolution_in_service_request.php
- https://canyongbs.atlassian.net/browse/AIDAPP-188
Fix issue with the data migration to populate TTR for already closed Service Requests throwing errors.
No.
No.
=> [AIDAPP-188]: Fix bug with TTR data migration

portals/knowledge-management/src/Pages/CreateServiceRequest.vue
- https://canyongbs.atlassian.net/browse/AIDAPP-186
> Updated the message from "Thank you for submitting a new request." to "Thank you. Your request has been submitted." when submitting a request.
> No
> No
=> [AIDAPP-186]: Update success message when submitting a request

app-modules/service-management/database/migrations/2024_07_15_104411_data_purge_time_to_resolution_feature_flag.php, app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ViewServiceRequest.php, app-modules/service-management/src/Observers/ServiceRequestObserver.php
- https://canyongbs.atlassian.net/browse/AIDAPP-190
> Cleanup "time_to_resolution" feature flag.
> No
> No
=> [AIDAPP-190] (Cleanup) Time To Resolution In Service request

package-lock.json, package.json
- https://canyongbs.atlassian.net/browse/AIDAPP-140
Updates `spectaql` to version that contains patch for CVE-2024-37890.
No
No
=> [AIDAPP-140]: Remediate issues related to CVE-2024-37890

app-modules/task/src/Filament/Resources/TaskResource/Components/TaskViewHeaderAction.php, app-modules/task/src/Filament/Resources/TaskResource/Pages/EditTask.php, app-modules/task/src/Notifications/TaskAssignedToUserNotification.php
- https://canyongbs.atlassian.net/browse/AIDAPP-175
Resolved view modal issue. 
No
No
=> [AIDAPP-175] Unexpected behavior when opening a task from the notifications bar

app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/EditKnowledgeBaseItem.php
- https://canyongbs.atlassian.net/browse/AIDAPP-196
>Change label 'Save Article Details' to 'Save' and 'Edit Article Properties' to 'Article Information' in edit knowledge management page.
>No.
> No.
=> [AIDAPP-196]: Improve knowledge management Save and Article Information buttons

app-modules/report/src/Filament/Pages/ServiceRequests.php
- https://canyongbs.atlassian.net/browse/AIDAPP-198
> Report grouping label updated from Service Requests to Service Management.
> No
> No
=> [AIDAPP-198]: Improve the label on the report grouping for the Report Library to Service Management

app-modules/report/src/Filament/Widgets/RecentServiceRequestsTable.php, app-modules/report/src/Filament/Widgets/TopServiceRequestTypesTable.php
- https://canyongbs.atlassian.net/browse/AIDAPP-199
> Display 5 results in both the Recent Service Requests table and the Top Request Types table.
> No
> No
=> [AIDAPP-199]: Improve the display of the tables in the Service Requests report in the Report Library

composer.lock
This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.48.17` branch.
**Before merging**, you need to:
- Checkout the `shift-ci-v10.48.17` branch
- Review **all** pull request comments for additional changes
- Run `composer update`
- Thoroughly test your application ([no tests?](https://laravelshift.com/laravel-test-generator), [no CI?](https://laravelshift.com/ci-generator))
=> Laravel 10.48.17 Shift

app-modules/inventory-management/src/Filament/Resources/AssetResource/Pages/ViewAsset.php
- https://canyongbs.atlassian.net/browse/AIDAPP-194
change asset view page in two columns.
No
No
=> [AIDAPP-194]: Enhance the display of assets by better utilizing the screen real estate

app/Filament/Clusters/ReportLibrary.php, app/Filament/Clusters/UsageAuditing.php, app/Filament/Pages/ProductHealth.php
- https://canyongbs.atlassian.net/browse/AIDAPP-201
> Change the menu order of Report center.
> No.
> No.
=> [AIDAPP-201]: Improve the order of the menu items in the Report Center

app-modules/knowledge-base/resources/views/filament/pages/badges.blade.php, app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/EditKnowledgeBaseItem.php
- https://canyongbs.atlassian.net/browse/AIDAPP-205
add badge for status.
No
No
=> [AIDAPP-205]: Introduce a badge that displays the current status (e.g., published) for a knowledge base article.

composer.lock, database/migrations/2024_08_01_175631_data_fix_image_ids_in_tiptap_content.php
- https://canyongbs.atlassian.net/browse/AIDAPP-214
Data fix for old images uploaded to the KB articles.
No
No
=> [AIDAPP-214]: Some knowledge base items will not load after last release

app/Notifications/SetPasswordNotification.php
- https://canyongbs.atlassian.net/browse/AIDAPP-212
> Correct the set password email URL.
> No
> No
=> [AIDAPP-212]: Correct set password email URL to update relative url to full path/absolute url

app-modules/knowledge-base/resources/views/filament/pages/badges.blade.php, app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/EditKnowledgeBaseItem.php
- https://canyongbs.atlassian.net/browse/AIDAPP-206
Introduce a badge that displays public or internal for a knowledge base article.
No
No
=> [AIDAPP-206]: Introduce a badge that displays public or internal for a knowledge base article.

app-modules/form/src/Actions/GenerateServiceRequestFeedbackFormEmbedCode.php, app-modules/form/src/Filament/Blocks/UploadFormFieldBlock.php, app-modules/portal/routes/api.php, app-modules/portal/routes/web.php, app-modules/portal/src/Actions/GeneratePortalEmbedCode.php, app-modules/portal/src/Filament/Pages/ManagePortalSettings.php, app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/CreateServiceRequestController.php, app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalController.php, app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalLogoutController.php, app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalRequestAuthenticationController.php, app-modules/portal/src/Http/Middleware/EnsureKnowledgeManagementPortalIsEnabled.php, app-modules/service-management/src/Http/Controllers/ServiceRequestFeedbackFormWidgetController.php, portals/knowledge-management/src/Services/GetAppContext.js
- https://canyongbs.atlassian.net/browse/AIDAPP-211
Refactor the primary url of the application portal
yes, run below commands,
npm run build
if any error will come because of tip top editor then first run composer ci  and then npm run build again.
No
=> [AIDAPP-211]: Refactor the primary url of the application portal

app-modules/knowledge-base/resources/views/filament/pages/badges.blade.php, database/migrations/2024_08_09_100519_drop_sessions_table.php
- https://canyongbs.atlassian.net/browse/AIDAPP-141
Remove table sessions
No
No
=> [AIDAPP-141]: Eliminate the legacy sessions management artifacts

app-modules/report/src/Filament/Widgets/ServiceRequestsStats.php
- https://canyongbs.atlassian.net/browse/AIDAPP-215
Accessing the report library generates an exception
No
No
=> [AIDAPP-215]: Accessing the report library generates an exception

app/Console/Commands/InitialMigration.php, docker/s6-overlay/s6-rc.d/initial-migration/dependencies, docker/s6-overlay/s6-rc.d/initial-migration/type, docker/s6-overlay/s6-rc.d/initial-migration/up, docker/s6-overlay/s6-rc.d/laravel-octane/dependencies, docker/s6-overlay/scripts/initial-migration
- https://canyongbs.atlassian.net/browse/AIDAPP-191
Add an initial migration task to s6-overlay to make local setup faster and easier.
No.
No.
=> [AIDAPP-191]: Add initial migration s6-overlay task

package-lock.json
- https://canyongbs.atlassian.net/browse/AIDAPP-219
Resolves https://github.com/canyongbs/aidingapp/security/dependabot/11.
No
No
=> [AIDAPP-219]: CVE-2024-39338

.github/actions/composer-dependency-setup/action.yml, .github/workflows/ci.yml, app-modules/service-management/src/Models/ChangeRequest.php, phpstan.neon.dist, phpunit-ci.xml
- https://canyongbs.atlassian.net/browse/AIDAPP-220
Resolves CI issue where "fatal: No names found, cannot describe anything." is thrown due to CI pulling a shallow clone of the repository.
No.
No.
=> [AIDAPP-220]: Fix "fatal: No names found, cannot describe anything." during CI/CD

.github/CODEOWNERS
- https://canyongbs.atlassian.net/browse/AIDAPP-221
Sets up CODEOWNERS for the repository.
No.
No.
=> [AIDAPP-221]: Setup CODEOWNERS

.github/workflows/ci.yml, .github/workflows/pull_requests.yml
- https://canyongbs.atlassian.net/browse/AIDAPP-221
Adjusts CI to work for Merge Queues.
No.
No.
=> [AIDAPP-221]: Setup Merge Queues

app-modules/service-management/src/Filament/Resources/ServiceRequestResource.php, app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ManageAssignment.php, app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ManageAssignments.php
- https://canyongbs.atlassian.net/browse/AIDAPP-232
> Modify the display of UI/UX to present 'Assignments' instead of 'Service Request Assignments'.
> No.
> No.
=> [AIDAPP-232]: Improve the display in the UI/UX for service request assignments

portals/knowledge-management/src/Pages/Home.vue, portals/knowledge-management/src/Pages/ViewCategory.vue
- https://canyongbs.atlassian.net/browse/AIDAPP-222
> Fixed the issue when Attempting to search by entering in a phrase followed by the return key while in the client portal does not work as expected.
> No
> No
=> [AIDAPP-222] Attempting to search by entering in a phrase followed by the return key while in the client portal does not work as expected.

app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource.php
- https://canyongbs.atlassian.net/browse/AIDAPP-226
Fixes bug thrown by global search when a result matches a KB Article.
No.
No.
=> [AIDAPP-226]: When performing a global search it sometimes generates an exception

app-modules/contact/src/Filament/Resources/ContactResource/Pages/ListContacts.php, app-modules/contact/src/Filament/Resources/ContactResource/Pages/ViewContact.php, app-modules/contact/src/Filament/Resources/ContactResource/RelationManagers/EngagementResponsesRelationManager.php, app-modules/contact/src/Filament/Resources/ContactSourceResource/Pages/CreateContactSource.php, app-modules/contact/src/Filament/Resources/ContactSourceResource/Pages/EditContactSource.php, app-modules/contact/src/Filament/Resources/ContactSourceResource/Pages/ViewContactSource.php, app-modules/contact/src/Filament/Resources/ContactStatusResource/Pages/ViewContactStatus.php, app-modules/engagement/src/Filament/Actions/EngagementCreateAction.php, app-modules/engagement/src/Filament/Concerns/EngagementResponseInfolist.php, app-modules/engagement/src/Filament/Resources/EngagementResource/Pages/ViewEngagement.php, app-modules/engagement/src/Filament/Resources/EngagementResource/RelationManagers/EngagementDeliverablesRelationManager.php, app-modules/engagement/src/Filament/Resources/EngagementResponseResource/Pages/ListEngagementResponses.php, app-modules/engagement/src/Filament/Resources/EngagementResponseResource/Pages/ViewEngagementResponse.php, app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseQualityResource/Pages/ViewKnowledgeBaseQuality.php, app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseStatusResource/Pages/ViewKnowledgeBaseStatus.php, app-modules/service-management/src/Filament/Concerns/ServiceRequestAssignmentInfolist.php, app-modules/service-management/src/Filament/Concerns/ServiceRequestHistoryInfolist.php, app-modules/service-management/src/Filament/Concerns/ServiceRequestUpdateInfolist.php, app-modules/service-management/src/Filament/Resources/ServiceRequestResource/RelationManagers/ServiceRequestUpdatesRelationManager.php, app-modules/service-management/src/Filament/Resources/ServiceRequestStatusResource/Pages/ViewServiceRequestStatus.php, app-modules/service-management/src/Filament/Resources/ServiceRequestUpdateResource.php, app-modules/service-management/src/Filament/Resources/ServiceRequestUpdateResource/Pages/ViewServiceRequestUpdate.php, app-modules/webhook/src/Filament/Resources/InboundWebhookResource/Pages/ViewInboundWebhook.php
- https://canyongbs.atlassian.net/browse/AIDAPP-227
> Remove usage of translateLabel() method
> No
> No
=> [AIDAPP-227]: Remove usage of translateLabel() method

app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalController.php
- https://canyongbs.atlassian.net/browse/AIDAPP-242
- https://canyongbs.atlassian.net/browse/AIDAPP-243
- https://canyongbs.atlassian.net/browse/AIDAPP-244
Fixes bug attempting to pull in incorrect conversion name.
No
No
=> [AIDAPP-242] & [AIDAPP-243] & [AIDAPP-244]: Fix portal rendering issues

composer.json, composer.lock
- https://canyongbs.atlassian.net/browse/AIDAPP-239
Resolve the security issue tracked under CVE-2024-45048
Run composer update command.
No
=> [AIDAPP-239]: Resolve the security issue tracked under CVE-2024-45048

composer.json, composer.lock
- https://canyongbs.atlassian.net/browse/AIDAPP-240
This is an extra fix on top of the original which removes our patch override and updates as the package has been backported in a recent update.
No
No
=> [AIDAPP-240]: Resolve the security issue tracked under CVE-2024-45046 | Remove our override and update base package

app-modules/contact/database/migrations/2024_09_04_192328_add_is_contact_generation_enabled_to_organizations_table.php, app-modules/contact/database/migrations/2024_09_05_085357_data_activate_contact_generation_enabled_feature_flag.php, app-modules/contact/src/Filament/Resources/OrganizationResource/Pages/CreateOrganization.php, app-modules/contact/src/Filament/Resources/OrganizationResource/Pages/EditOrganization.php, app-modules/contact/src/Models/Organization.php, app/Enums/FeatureFlag.php
- https://canyongbs.atlassian.net/browse/AIDAPP-230
> Add "Automatically generate contact record on login" toggle when creating and editing any organization.
> No
> Yes. "ContactGenerationEnabled"
=> [AIDAPP-230]: Introduce setting to automatically generate a contact

portals/knowledge-management/src/Components/Footer.vue
- https://canyongbs.atlassian.net/browse/AIDAPP-248
Enhance the footer to display better separation from the article itself
Run below command and check with hard refresh.
npm run build
No
=> [AIDAPP-248]: Enhance the footer to display better separation from the article itself

portals/knowledge-management/src/Pages/ViewArticle.vue
- https://canyongbs.atlassian.net/browse/AIDAPP-249
Enhance the header in the support portal to better separate the article details from the article content
Run npm build command and check with hard refresh.
No
=> [AIDAPP-249]: Enhance the header in the support portal to better separate the article details from the article content

app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalCategoryController.php, portals/knowledge-management/src/Pages/ViewCategory.vue
- https://canyongbs.atlassian.net/browse/AIDAPP-245
> When viewing a list of articles within a category, paginate the results
> No
> No
=> [AIDAPP-245]: When viewing a list of articles within a category, paginate the results

composer.json, composer.lock
- https://canyongbs.atlassian.net/browse/AIDAPP-855
Updates `canyongbs/filament-tiptap-editor`
No
No
=> [ADVAPP-855]: Composer update canyongbs/filament-tiptap-editor

app-modules/knowledge-base/database/migrations/2024_09_12_071605_add_portal_view_count_in_knowledge_base_articles_table.php, app-modules/knowledge-base/src/Models/KnowledgeBaseItem.php, app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalArticleController.php, database/migrations/2024_09_12_073239_portal_view_count_feature_flag.php, portals/knowledge-management/src/Pages/ViewArticle.vue
- https://canyongbs.atlassian.net/browse/AIDAPP-250
> Create new feature where every time the article is clicked for view it count increases and end user can see total number of view on that article in the view article page.
> No.
> `portal_view_count`
=> [AIDAPP-250]: Track portal views of articles and display them as article metadata

app/Providers/HealthServiceProvider.php, docker-compose.dev.yml
- https://canyongbs.atlassian.net/browse/AIDAPP-260
> Update the App URL in the PingCheck class instead of checking the IP address (1.1.1.1).
> Might need to restart the docker container as docker-compose.dev.yml file is change
> No
=> [AIDAPP-260]: Product Ping Health check is failing for all environments

portals/knowledge-management/src/App.vue, portals/knowledge-management/src/Pages/Home.vue
- https://canyongbs.atlassian.net/browse/AIDAPP-269
When accessing the portal, the footer color is not consistently displayed.
No
No
=> [AIDAPP-269]: When accessing the portal, the footer color is not consistently displayed.

app-modules/portal/routes/web.php
- N/A
Fixes route naming conflict with service requests portal endpoints.
No
No
=> [Bugfix]: Fix naming issues with service request routes

composer.json, composer.lock, package-lock.json
- https://canyongbs.atlassian.net/browse/AIDAPP-292
Resolves security issues tracked under CVE-2024-47186 and updates abandoned packages to report to remain consistent after Composer updates.
No
No
=> [AIDAPP-292]: Resolve the security issue tracked under CVE-2024-47186

portals/knowledge-management/src/App.vue
- https://canyongbs.atlassian.net/browse/AIDAPP-285
> After a contact authenticates in the portal, a list of service requests assigned to a contact are not showing up
> No
> No
=> [AIDAPP-285]: After a contact authenticates in the portal, a list of service requests assigned to a contact are not showing up

portals/knowledge-management/src/Pages/ViewArticle.vue
- https://canyongbs.atlassian.net/browse/AIDAPP-286
> Improve the styling of articles by reducing the weight of the article titlel.
> No.
> No.
=> [AIDAPP-286]: Improve the styling of articles by reducing the weight of the article title.

stubs/feature.stub
- https://canyongbs.atlassian.net/browse/AIDAPP-288
Fix path defined in stub for Feature Flags.
No
No
=> [AIDAPP-288]: Fix path in FeatureFlag stub

app-modules/contact/src/Filament/Resources/ContactResource/RelationManagers/ServiceRequestsRelationManager.php
- https://canyongbs.atlassian.net/browse/AIDAPP-276
> When editing a Service Request through the Contact profile Type and Priority are not set in the form.
> No.
> No.
=> [AIDAPP-276]: When editing a Service Request through the Contact profile Type and Priority are not set in the form

app-modules/service-management/database/factories/ServiceRequestStatusFactory.php, app-modules/service-management/database/migrations/2024_10_07_175810_add_is_system_protected_column_to_service_request_statuses_table.php, app-modules/service-management/database/migrations/2024_10_07_180708_data_seed_system_protected_new_status_for_service_request_statuses.php, app-modules/service-management/database/seeders/ServiceRequestStatusSeeder.php, app-modules/service-management/resources/views/filament/pages/service-request-type-lock-icon.blade.php, app-modules/service-management/src/Filament/Resources/ServiceRequestStatusResource/Pages/ListServiceRequestStatuses.php, app-modules/service-management/src/Filament/Resources/ServiceRequestStatusResource/Pages/ViewServiceRequestStatus.php, app-modules/service-management/src/Models/ServiceRequestStatus.php, app-modules/service-management/src/Policies/ServiceRequestStatusPolicy.php, app-modules/service-management/tests/ServiceRequestStatus/CreateServiceRequestStatusTest.php, app-modules/service-management/tests/ServiceRequestStatus/EditServiceRequestStatusTest.php, app-modules/service-management/tests/ServiceRequestStatus/ListServiceRequestStatusesTest.php, app-modules/service-management/tests/ServiceRequestStatus/ViewServiceRequestStatusTest.php, app/Features/ServiceRequestStatusSystemProtection.php, database/migrations/2024_10_07_185927_data_activate_feature_flag_service_request_status_system_protection.php, database/migrations/2024_10_07_203357_create_function_to_prevent_modification_of_system_protected_rows.php, database/migrations/2024_10_07_204633_create_trigger_to_apply_modification_prevention_for_system_protected_service_request_statuses.php
- https://canyongbs.atlassian.net/browse/AIDAPP-284
Sets up system protection for the Service Request Status "New". Adds protections and both the policy and database level.
No
Feature Flags Added:
- `ServiceRequestStatusSystemProtection`
=> [AIDAPP-284]: Ensure that the system status of New cannot be deleted or edited

app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/CreateServiceRequestController.php, app-modules/portal/src/Livewire/RenderKnowledgeManagementPortal.php, portals/knowledge-management/src/App.vue
- https://canyongbs.atlassian.net/browse/AIDAPP-298
>Updated service portal meta title Knowledge "Management Portal - Aiding App" to "Help Center".
> No.
> No.
=> [AIDAPP-298]: Improve the service portal title so that it is more accurate

app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource.php, app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/ListKnowledgeBaseItems.php, app/Filament/Clusters/KnowledgeManagement.php
- https://canyongbs.atlassian.net/browse/AIDAPP-310
Enhance the description of Knowledge Management by renaming this function to the more common language in ITSM
No
No
=> [AIDAPP-310]: Enhance the description of Knowledge Management by renaming this function to the more common language in ITSM

app-modules/knowledge-base/database/migrations/2024_10_14_102603_add_featured_column_in_knowledge_base_articles_table.php, app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/CreateKnowledgeBaseItem.php, app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/EditKnowledgeBaseItemMetadata.php, app-modules/knowledge-base/src/Models/KnowledgeBaseItem.php, app-modules/portal/src/DataTransferObjects/KnowledgeBaseArticleData.php, app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalArticleController.php, app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalCategoryController.php, app/Features/FeaturedArticle.php, database/migrations/2024_10_14_102853_data_activate_featured_flag_featured_article.php, portals/knowledge-management/src/Components/Article.vue, portals/knowledge-management/src/Components/Tags.vue, portals/knowledge-management/src/Pages/ViewArticle.vue
- https://canyongbs.atlassian.net/browse/AIDAPP-307
> Add a new Toggle  to identify an article as 'Featured'.
And show 'Featured' Tag for articles in portal view if featured is set on.
> No.
> Feature Flags:
FeaturedArticle
=> [AIDAPP-307]: Introduce the ability to mark an article as "Featured" for display in the client portal

app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalCategoryController.php
…he display of articles
- https://canyongbs.atlassian.net/browse/AIDAPP-305
In the article view page, modify the pagination approach to improve the display of articles
No
No
=> [AIDAPP-305]: In the article view page, modify the pagination approach to improve the display of articles

_ide_helper_models.php, app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalSearchController.php
- https://canyongbs.atlassian.net/browse/AIDAPP-321
Fixes a bug with portal search.
No
No
=> [AIDAPP-321]: Portal search loads forever and throws an error

resources/views/filament/forms/components/heading-three.blade.php
- https://canyongbs.atlassian.net/browse/AIDAPP-325
> Update heading tag to h3 in heading-three.blade.php
> No
> No
=> [AIDAPP-325]: Fix Filament Form Header H3 to actually return an actual h3 element

resources/views/filament/forms/components/paragraph.blade.php
- https://canyongbs.atlassian.net/browse/AIDAPP-326
> Update heading tag to paragraph tag in paragraph.blade.php file.
> No
> No
=> [AIDAPP-326]: Fix Filament Form Paragraph component to actually return a p tag

app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/ListKnowledgeBaseItems.php
- https://canyongbs.atlassian.net/browse/AIDAPP-328
>  Update the knowledge base article list view format for the date..
> No.
> No.
=> [AIDAPP-328]: Update the knowledge base article list view format for the date.

app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/EditServiceRequestTypeNotifications.php
- https://canyongbs.atlassian.net/browse/AIDAPP-324
> Update the Notifications icon in the service request types.
> No.
> No.
=> [AIDAPP-324]: Update the Notifications icon in the service request types

.github/actions/composer-dependency-setup/action.yml, Dockerfile
- https://canyongbs.atlassian.net/browse/AIDAPP-331
Switches to APCu composer classmap autoloading.
No
No
=> [AIDAPP-331]: Change to APCu composer classmaps

app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php
- https://canyongbs.atlassian.net/browse/AIDAPP-335
> Include an Unassigned badge in the list view for service requests.
> No.
> No.
=> [AIDAPP-335]: Include an Unassigned badge in the list view for service requests

app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php
- https://canyongbs.atlassian.net/browse/AIDAPP-334
> Enhance the information displayed in the main service request list.
> No.
> No.
=> [AIDAPP-334]: Enhance the information displayed in the main service request list

app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php, app-modules/service-management/tests/ServiceRequest/ListServiceRequestsTest.php
- https://canyongbs.atlassian.net/browse/AIDAPP-336
> Include a "Unassigned" filter (checkbox) in the list view for service requests.
> No.
> No.
=> [AIDAPP-336]: Include a "Unassigned" filter (checkbox) in the list view for service requests

app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php
- https://canyongbs.atlassian.net/browse/AIDAPP-337
Fixes cap casing of Assigned To and makes requested field togglable.
No
No
=> [AIDAPP-337]: Make certain columns displayed in the service request list view able to be hidden

app-modules/knowledge-base/database/migrations/2024_10_30_184951_data_add_remainig_slug_in_knowledge_base_categories_table.php
- https://canyongbs.atlassian.net/browse/AIDAPP-340
A quick bugfix to resolve issues with KB category slug migration
No
No
=> [AIDAPP-340]: Fix slug data migration

composer.lock
- https://canyongbs.atlassian.net/browse/AIDAPP-345
- https://canyongbs.atlassian.net/browse/AIDAPP-344
- https://canyongbs.atlassian.net/browse/AIDAPP-342
- https://canyongbs.atlassian.net/browse/AIDAPP-349
Updates vulnerable dependencies.
No
No
=> [AIDAPP-345] & [AIDAPP-344] & [AIDAPP-342] & [AIDAPP-349]: Resolve security issues

app-modules/service-management/src/Observers/ServiceRequestObserver.php, app-modules/service-management/tests/ServiceRequest/CreateServiceRequestTest.php
- https://canyongbs.atlassian.net/browse/AIDAPP-333
> Introduce the Assignment Type Individual so that all new service requests are assigned to a specific manager.
> No
> No
=> [AIDAPP-333]: Introduce the Assignment Type Individual so that all new service requests are assigned to a specific manager.

database/migrations/2024_12_05_000938_data_fix_super_admin_rename.php
- https://canyongbs.atlassian.net/browse/AIDAPP-376
Fixes issues with role rename.
No
No
=> [AIDAPP-376]: Fix issues with super admin role rename

app-modules/audit/src/Filament/Pages/ManageAuditSettings.php, app-modules/authorization/src/Filament/Pages/ManageAzureSsoSettings.php, app-modules/authorization/src/Filament/Pages/ManageGoogleSsoSettings.php, app-modules/integration-aws-ses-event-handling/src/Filament/Pages/ManageAmazonSesSettings.php, app-modules/integration-aws-ses-event-handling/tests/Feature/Filament/ManageAmazonSesSettingsTest.php, app-modules/integration-google-analytics/src/Filament/Pages/ManageGoogleAnalyticsSettings.php, app-modules/integration-google-recaptcha/src/Filament/Pages/ManageGoogleRecaptchaSettings.php, app-modules/integration-microsoft-clarity/src/Filament/Pages/ManageMicrosoftClaritySettings.php, app-modules/integration-twilio/src/Filament/Pages/ManageTwilioSettings.php, app-modules/portal/src/Filament/Pages/ManagePortalSettings.php, app-modules/theme/src/Filament/Pages/ManageBrandConfigurationSettings.php, app-modules/webhook/src/Policies/InboundWebhookPolicy.php, app/Filament/Clusters/GlobalSettings.php, app/Filament/Clusters/ProductIntegrations.php, app/Filament/Pages/AmazonS3.php, app/Filament/Pages/ManageLicenseSettings.php, app/Providers/Filament/AdminPanelProvider.php, database/migrations/2024_12_03_064748_seed_permissions_remove_specific_global_settings_permissions.php, tests/Feature/Filament/AmazonS3Test.php
- https://canyongbs.atlassian.net/browse/AIDAPP-369
> Refactor the navigation experience for managing product administration
> No
> No
=> [AIDAPP-369]: Refactor the navigation experience for managing product administration

app-modules/license-management/src/Filament/Resources/ProductResource.php, app-modules/report/src/Filament/Pages/ServiceRequests.php, app-modules/service-management/src/Filament/Resources/ChangeRequestResource.php, app-modules/task/src/Filament/Resources/TaskResource.php
- https://canyongbs.atlassian.net/browse/AIDAPP-368
> Fix navigation item order for Contract Management
> No
> No.
=> [AIDAPP-368]: Fix navigation item order for Contract Management

app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php
- https://canyongbs.atlassian.net/browse/AIDAPP-379
>  Display service request status in the list view of service requests.
> No.
> No.
=> [AIDAPP-379]: Display service request status in the list view of service requests

app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php
- https://canyongbs.atlassian.net/browse/AIDAPP-387
> Limit the length of the description displayed in the service request list view table
> No
> No
=> [AIDAPP-387]: Limit the length of the description displayed in the service request list view table

app-modules/service-management/src/DataTransferObjects/ServiceRequestDataObject.php, app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php
- https://canyongbs.atlassian.net/browse/AIDAPP-385
> Fix issue when attempting to create a service request through the administration interface an exception is generated.
> No.
> No.
=> [AIDAPP-385]: Fix issue when attempting to create a service request through the administration interface an exception is generated

Dockerfile
- https://canyongbs.atlassian.net/browse/AIDAPP-383
Updates RoadRunner.
No
No
=> [AIDAPP-383]: Update RoadRunner Binary to v2024.3.0

app-modules/service-management/src/Filament/Resources/ChangeRequestStatusResource.php, app-modules/service-management/src/Filament/Resources/ChangeRequestTypeResource.php, app-modules/service-management/src/Filament/Resources/ServiceRequestFormResource.php, app-modules/service-management/src/Filament/Resources/ServiceRequestStatusResource.php, app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource.php, app-modules/service-management/src/Filament/Resources/SlaResource.php
- https://canyongbs.atlassian.net/browse/AIDAPP-391
> Improve the organization of Service Management settings
> No
> No
=> [AIDAPP-391]: Improve the organization of Service Management settings

app-modules/portal/src/Filament/Pages/ManagePortalSettings.php
- https://canyongbs.atlassian.net/browse/AIDAPP-390
Relocate Client Portal in Global Administration to Product Administration
No
No
=> [AIDAPP-390]: Relocate Client Portal in Global Administration to Product Administration

app-modules/authorization/src/Filament/Resources/PermissionResource.php, app-modules/authorization/src/Filament/Resources/RoleResource.php, app-modules/division/src/Filament/Resources/DivisionResource.php, app-modules/team/src/Filament/Resources/TeamResource.php, app/Filament/Resources/SystemUserResource.php, app/Filament/Resources/UserResource.php, app/Providers/Filament/AdminPanelProvider.php
- https://canyongbs.atlassian.net/browse/AIDAPP-401
>  Update the label used for People Administration to User Management in the navigation group.
> No.
>  No
=> [AIDAPP-401]: Update the label used for People Administration to User Management in the navigation group

app-modules/service-management/database/factories/ServiceRequestTypeEmailTemplateFactory.php, app-modules/service-management/database/migrations/2024_12_30_090123_create_service_request_type_email_templates_table.php, app-modules/service-management/database/migrations/2025_01_03_091338_data_activate_service_request_type_email_template_feature.php, app-modules/service-management/src/Enums/ServiceRequestEmailTemplateType.php, app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource.php, app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/ServiceRequestTypeEmailTemplatePage.php, app-modules/service-management/src/Models/ServiceRequestType.php, app-modules/service-management/src/Models/ServiceRequestTypeEmailTemplate.php, app-modules/service-management/src/Providers/ServiceManagementServiceProvider.php, app-modules/service-management/tests/ServiceRequestType/CreateServiceRequestTypeTest.php, app-modules/service-management/tests/ServiceRequestType/RequestFactories/ServiceRequestTypeEmailTemplateRequestFactory.php, app-modules/service-management/tests/ServiceRequestType/ServiceRequestTypeEmailTemplatePageTest.php, app/Features/ServiceRequestTypeEmailTemplateFeature.php
- https://canyongbs.atlassian.net/browse/AIDAPP-394
> Create email templates in the service request types that govern the emails that are sent out for a customer
> No
> `ServiceRequestTypeEmailTemplateFeature`
=> [AIDAPP-394]: Create email templates in the service request types that govern the emails that are sent out for a customer

app-modules/service-management/src/Enums/SystemServiceRequestClassification.php, app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Actions/ChangeServiceRequestStatusBulkAction.php, app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php, app/Support/BulkProcessingMachine.php
Signed-off-by: Dan Harrin <dan.harrin@canyongbs.com>
- https://canyongbs.atlassian.net/browse/AIDAPP-422
Introduces `BulkProcessingMachine` to process many records, performing checks and notifying the user about the results. Follows existing rules from `ServiceRequestPolicy` for updating a request.
No
No
=> [AIDAPP-422]: Introduce bulk service request action to change status

app/Filament/Pages/ProductHealth.php, database/migrations/2025_01_21_111815_seed_permissions_delete_view_product_health_dashboard_permissions.php
- https://canyongbs.atlassian.net/browse/AIDAPP-426
> Change product health position from Report center group to Global Administration
> No
> No
=> [AIDAPP-426]: Relocate product health in navigation

app/Filament/Widgets/ListServiceRequestTableWidgets.php
- https://canyongbs.atlassian.net/browse/AIDAPP-430
> Apply the filter to see open service requests to the homepage dashboard.
> No.
> No.
=> [AIDAPP-430]: Apply the filter to see open service requests to the homepage dashboard

app-modules/service-management/src/Enums/ServiceRequestTypeAssignmentTypes.php, app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/EditServiceRequestTypeAssignments.php
- https://canyongbs.atlassian.net/browse/AIDAPP-425
> Implement radio button descriptions for assignment types
> No
> No
=> [AIDAPP-425]: Implement radio button descriptions for assignment types

app/Filament/Widgets/ListServiceRequestTableWidgets.php
- https://canyongbs.atlassian.net/browse/AIDAPP-431
> Make all columns toggleable (show/hide) except service request # on the home page
> No
> No
=> [AIDAPP-431]: Make all columns toggleable (show/hide) except service request # on the home page

app/Console/Kernel.php
- https://canyongbs.atlassian.net/browse/AIDAPP-440
Sets up Model pruning for `HealthCheckResultHistoryItem`.
No
No
=> [AIDAPP-440]: Setup pruning for HealthCheckResultHistoryItem

app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Actions/AddServiceRequestUpdateBulkAction.php, app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php, app-modules/service-management/tests/ServiceRequest/Actions/AddServiceRequestUpdateBulkActionTest.php
- https://canyongbs.atlassian.net/browse/AIDAPP-423
> Introduce bulk service request action to add service request update.
> No
> No
=> [AIDAPP-423]: Introduce bulk service request action to add a request update

resources/css/filament/admin/theme.css
- https://canyongbs.atlassian.net/browse/AIDAPP-438
> Enhance the ability to distinguish the main navigation from the page itself
> No
> No
=> [AIDAPP-438]: Enhance the ability to distinguish the main navigation from the page itself

Dockerfile
- https://canyongbs.atlassian.net/browse/AIDAPP-435
> Update Roadrunner to 2024.3.2.
> No.
> No.
=> [AIDAPP-435]: Update Roadrunner to 2024.3.2

app-modules/authorization/src/Enums/LicenseType.php, app/DataTransferObjects/LicenseManagement/LicenseLimitsData.php, app/Filament/Forms/Components/Licenses.php, app/Filament/Pages/ManageLicenseSettings.php, app/Http/Requests/Tenants/CreateTenantRequest.php, app/Http/Requests/Tenants/SyncTenantRequest.php, database/migrations/2025_02_04_134709_data_remove_conversational_ai_seats_from_licenses_table.php
- https://canyongbs.atlassian.net/browse/AIDAPP-357
> Remove Conversational AI seats from license management and related validation.
> No
> No
=> [AIDAPP-357]: Remove the ConversationalAi License Type

app-modules/service-management/src/Filament/Resources/ServiceRequestResource/RelationManagers/AssignedToRelationManager.php, app-modules/service-management/src/Observers/ServiceRequestAssignmentObserver.php, app-modules/service-management/tests/ServiceRequest/AssignedToRelationManagerTest.php, app-modules/service-management/tests/ServiceRequest/CreateServiceRequestTest.php, app-modules/service-management/tests/ServiceRequest/ListServiceRequestsTest.php
- https://canyongbs.atlassian.net/browse/AIDAPP-436
Intermittent error occurs when clicking the "Assign to Me" button in service request assignments
No
No
=> [AIDAPP-436]: Intermittent error occurs when clicking the "Assign to Me" button in service request assignments

app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ViewServiceRequest.php
- https://canyongbs.atlassian.net/browse/AIDAPP-448
> Optimize display when viewing a service request.
> No.
> No.
=> [AIDAPP-448]: Optimize display when viewing a service request

.gitignore
- https://canyongbs.atlassian.net/browse/AIDAPP-450
> Add .psysh_history to the .gitignore
> No
> No
=> [AIDAPP-450]: Add .psysh_history to the .gitignore

app-modules/authorization/tests/Feature/Filament/Resources/User/ListUsersTest.php, app/Filament/Resources/UserResource.php
- https://canyongbs.atlassian.net/browse/AIDAPP-461
> Enhance the user list experience by introducing filters for each license type
> No
> No
=> [AIDAPP-461]: Enhance the user list experience by introducing filters for each license type

app/Filament/Imports/UserImporter.php, app/Filament/Resources/UserResource.php, app/Filament/Resources/UserResource/Pages/ListUsers.php, app/Rules/EmailNotInUseOrSoftDeleted.php
- https://canyongbs.atlassian.net/browse/AIDAPP-462
>Add user import functionality with email validation
> No
> No
=> [AIDAPP-462]: Introduce ability to import a list of users

Dockerfile
- https://canyongbs.atlassian.net/browse/AIDAPP-452
> Update Roadrunner version to 2024.3.4 in Dockerfile.
> No
> No
=> [AIDAPP-452]: Update to RoadRunner v2024.3.4

app-modules/report/src/Filament/Widgets/ServiceRequestsStats.php, app-modules/report/src/Filament/Widgets/TopServiceRequestTypesTable.php
- https://canyongbs.atlassian.net/browse/AIDAPP-451
> Solve the issue when opening the report library it was giving carbon issue.
> No
> No
=> [AIDAPP-451]: Accessing the report library generates an exception

app-modules/contact/src/Models/Contact.php, app-modules/task/database/factories/TaskFactory.php, app-modules/task/database/migrations/2025_02_14_140238_drop_concern_type_column_from_tasks_table.php, app-modules/task/src/Filament/Concerns/TaskEditForm.php, app-modules/task/src/Filament/Concerns/TaskForm.php, app-modules/task/src/Filament/Resources/TaskResource/Pages/CreateTask.php, app-modules/task/src/Models/Task.php, app-modules/task/tests/RequestFactories/EditTaskRequestFactory.php, app/Livewire/TaskKanban.php
- https://canyongbs.atlassian.net/browse/AIDAPP-470
> Update and optimize the relationships between tasks and contacts
> No
> No
=> [AIDAPP-470]: Update and optimize the relationships between tasks and contacts

app-modules/authorization/tests/Feature/Filament/Resources/User/ListUsersTest.php, app/Filament/Resources/UserResource.php, app/Filament/Resources/UserResource/Actions/AssignLicensesBulkAction.php
- https://canyongbs.atlassian.net/browse/AIDAPP-459
> add bulk action for assigning licenses to users with permission
> No
> No
=> [AIDAPP-459]: Introduce new users list view bulk license assign operation

app/Filament/Resources/UserResource.php, app/Models/User.php
- https://canyongbs.atlassian.net/browse/AIDAPP-475
> Add team assignment to the view and edit pages for managing users
> No
> No
=> [AIDAPP-475]: Add team assignment to the view and edit pages for managing users

app-modules/contact/src/Filament/Resources/ContactResource/Pages/CreateContact.php, app-modules/contact/src/Filament/Resources/ContactResource/Pages/EditContact.php, app-modules/contact/src/Filament/Resources/ContactResource/Pages/ViewContact.php
- https://canyongbs.atlassian.net/browse/AIDAPP-476
Display the relationship a contact has to an organization in the classification section of the record
No
No
=> [AIDAPP-476]: Display the relationship a contact has to an organization in the classification section of the record

composer.json
- https://canyongbs.atlassian.net/browse/AIDAPP-480
> Update license from MIT to Elastic-2.0 in composer.json
> No.
> No.
=> [AIDAPP-480]: Update the license in the composer.json

portals/knowledge-management/src/App.vue, widgets/service-request-feedback-form/src/App.vue, widgets/service-request-form/src/App.vue
- https://canyongbs.atlassian.net/browse/AIDAPP-485
Fixes the path to the portal and widget CSS files.
No
No
=> [AIDAPP-485]: Fix path to generated portal and widget css

composer.json, composer.lock
- https://canyongbs.atlassian.net/browse/AIDAPP-477
Resolves the `CVE-2021-44906` security vulnerability in our container by patching `spatie/laravel-health` to the commit where the underlying dependencies are updated. This is a temporary fix until they make an official release making this change.
No
No
=> [AIDAPP-477]: Resolve the security issue tracked under CVE-2021-44906

composer.lock
- https://canyongbs.atlassian.net/browse/AIDAPP-486
Fixes the lock file that is not in sync with the `composer.json`.
No
No
=> [AIDAPP-486]: Fix outdated lock file

app-modules/report/Abstract/EngagementReport.php, app-modules/report/src/Abstract/EngagementReport.php, app-modules/report/src/Filament/Pages/TaskManagement.php, app-modules/report/src/Filament/Widgets/MostRecentTasksTable.php, app-modules/report/src/Filament/Widgets/TaskCumulativeCountLineChart.php, app-modules/report/src/Filament/Widgets/TaskStats.php
- https://canyongbs.atlassian.net/browse/AIDAPP-467
> Create report for the report library for Task Management
> No
> No
=> [AIDAPP-467]: Create report for the report library for Task Management

app-modules/contact/database/factories/OrganizationFactory.php, app-modules/contact/src/Filament/Resources/OrganizationResource/Pages/CreateOrganization.php, app-modules/contact/src/Filament/Resources/OrganizationResource/Pages/EditOrganization.php, app-modules/contact/tests/Organization/RequestFactories/EditOrganizationRequestFactory.php
- https://canyongbs.atlassian.net/browse/AIDAPP-491
> Improve phone inputs for organizations
> No
> No
=> [AIDAPP-491]: Improve phone inputs for organizations

app/Multitenancy/Tasks/SwitchTenantDatabasesTask.php
- https://canyongbs.atlassian.net/browse/AIDAPP-514
Fixes an issue with batch job storage being put in the Landlord database during Tenant requests.
No
No
=> [AIDAPP-514]: Fix the storage of job batches so they are properly managed within tenants

app-modules/contact/src/Models/Contact.php, app/Enums/Feature.php, app/Models/Authenticatable.php, app/Models/SystemUser.php, app/Providers/AuthServiceProvider.php
- https://canyongbs.atlassian.net/browse/AIDAPP-515
This is a temporary fix in the right direction for authentication issues when submitting items to Aiding App when logged in as a Contact. Things are expecting the Authenticatble class. Later we will refactor to work better between the different User types.
No
No
=> [AIDAPP-515]: An error is thrown when a Contact submits a Service Request through the portal

app-modules/audit/src/Providers/AuditServiceProvider.php, app-modules/authorization/src/Providers/AuthorizationServiceProvider.php
Signed-off-by: Dan Harrin <dan.harrin@canyongbs.com>
- https://canyongbs.atlassian.net/browse/AIDAPP-524
Registers config correctly to avoid issues with caching.
No
No
=> [AIDAPP-524]: Fix configuration loading issues while cached

app-modules/contract-management/src/Filament/Resources/ContractResource.php, app-modules/license-management/src/Filament/Resources/ProductResource.php, app/Providers/Filament/AdminPanelProvider.php
- https://canyongbs.atlassian.net/browse/AIDAPP-528
Introduce purchasing as a navigation group
No
No
=> [AIDAPP-528]: Introduce purchasing as a navigation group

app-modules/license-management/src/Models/ProductLicense.php, app-modules/license-management/src/Models/Scopes/AuthorizeLicensesScope.php
- https://canyongbs.atlassian.net/browse/AIDAPP-526
> Restrict the visibility of a license record to the creator and assigned party only
> No
> No
=> [AIDAPP-526]: Restrict the visibility of a license record to the creator and assigned party only

stubs/migration.create.stub, stubs/migration.stub, stubs/migration.update.stub
- https://canyongbs.atlassian.net/browse/AIDAPP-518
> Overwrite the migration stub to use the tpetry/laravel-postgresql-enhanced classes
> No
> No
=> [AIDAPP-518]: Overwrite the migration stub to use the tpetry/laravel-postgresql-enhanced classes

app-modules/portal/src/DataTransferObjects/ServiceRequestData.php, portals/knowledge-management/src/Components/Header.vue, portals/knowledge-management/src/Components/HelpCenter.vue, portals/knowledge-management/src/Components/Services.vue, portals/knowledge-management/src/Pages/ViewServiceRequest.vue, portals/knowledge-management/src/portal.js
- https://canyongbs.atlassian.net/browse/AIDAPP-520
> Relocate service request information currently in home after logging in under new "Service" area of the updated navigation
> No
> No
=> [AIDAPP-520]: Relocate service request information currently in home after logging in under new "Service" area of the updated navigation

phpstan.neon.dist
- https://canyongbs.atlassian.net/browse/AIDAPP-537
Brings back the ignore and ignores if it is not found. We will need this once all in the baseline are resolved.
No
No
=> [AIDAPP-537]: Bring the ignore back that we will need for Larastan

phpstan.neon.dist
- https://canyongbs.atlassian.net/browse/AIDAPP-538
Until all linting is fixed we will ignore this for now.
No
No
=> [AIDAPP-538]: Disable error report of unmatched ignored errors

Dockerfile
- https://canyongbs.atlassian.net/browse/AIDAPP-548
> Minor upgrade for nodejs/node.
> No.
> No.
=> [AIDAPP-548]: Minor upgrade for nodejs/node

Dockerfile
- https://canyongbs.atlassian.net/browse/AIDAPP-546
Update RoadRunner binary
No
No
=> [AIDAPP-546]: Update RoadRunner binary 

composer.json, composer.lock
- https://canyongbs.atlassian.net/browse/AIDAPP-547
> Update canyongbs/common to version 1.1.1.
> No.
> No.
=> [AIDAPP-547]: Update canyongbs/common to version 1.1.1

app-modules/task/src/Filament/Resources/TaskResource.php, app/Filament/Pages/Projects.php, database/migrations/2025_04_09_153451_seed_permissions_project_permissions.php
- https://canyongbs.atlassian.net/browse/AIDAPP-545
> Introduce the navigation item for Projects under Project Management.
> No.
> No.
=> [AIDAPP-545]: Introduce the navigation item for Projects under Project Management.

package-lock.json, package.json
- https://canyongbs.atlassian.net/browse/AIDAPP-554
Updates `vite` to resolve CVE-2025-32395.
Also updates the `devops` submodule to stay up to date with it's `main` branch.
No
No
=> [AIDAPP-554]: Resolve the security issue tracked under CVE-2025-32395

package-lock.json
- https://canyongbs.atlassian.net/browse/AIDAPP-562
Updates `esbuild` to [v0.25.3](https://github.com/evanw/esbuild/releases/tag/v0.25.3) so that we get a patch for https://github.com/advisories/GHSA-g9pc-8g42-g6vq
No
No
=> [AIDAPP-562]: Resolve the security issue tracked under CVE-2025-22871

database/migrations/2025_04_16_195003_tmp_data_migrate_team_user_id_to_users_table.php
- https://canyongbs.atlassian.net/browse/AIDAPP-569
Resolves an issue with migration chunking
No
No
=> [AIDAPP-569] : Update Migration

composer.lock, package-lock.json, package.json
- https://canyongbs.atlassian.net/browse/AIDAPP-572
Update `vite` to [v6.3.4](https://github.com/vitejs/vite/releases/tag/v6.3.4)
No
No
=> [AIDAPP-572]: Resolve the security issue tracked under CVE-2025-46565

Dockerfile, package.json
- N/A
Fixes dubious ownership and other issues during the deployment build.
No
No
=> [Bugfix]: Docker Build Fix

composer.json, composer.lock
- https://canyongbs.atlassian.net/browse/AIDAPP-599
Fix bug with Tiptap by updating the plugin.
No
No
=> [AIDAPP-599]: Some users are reporting that the rich text editor fails to load when editing existing articles in the administrative experience

app/Models/Contracts/HasTags.php, app/Models/NotificationSettingPivot.php, app/Models/Scopes/EducatableSearch.php, app/Models/Scopes/EducatableSort.php, app/Models/Scopes/HasLicense.php, app/Models/Scopes/LicensedToEducatable.php, app/Models/Scopes/SearchBy.php, app/Models/Scopes/SetupIsComplete.php, app/Models/Scopes/TagsForClass.php, app/Models/Scopes/TagsForType.php, app/Models/States/StateMachine.php, app/Models/SystemUser.php, app/Models/User.php, app/Multitenancy/Exceptions/UnableToResolveTenantForEncryptionKey.php, app/Providers/AuthServiceProvider.php, app/Providers/MultiConnectionParallelTestingServiceProvider.php, app/Rules/EmailNotInUseOrSoftDeleted.php, app/Settings/OlympusSettings.php, app/Support/BulkProcessingMachine.php, database/migrations/2024_07_10_085735_data_update_value_of_time_to_resolution_in_service_request.php, database/migrations/2024_08_01_175631_data_fix_image_ids_in_tiptap_content.php, phpstan-baseline.php, phpstan.neon.dist, tests/Helpers.php
- https://canyongbs.atlassian.net/browse/AIDAPP-591
> Scan and improve underlying codebase.
> No.
> No.
=> [AIDAPP-591]: Scan and improve underlying codebase

app-modules/alert/src/Observers/AlertObserver.php, app-modules/contact/src/Filament/Resources/ContactResource/Pages/ManageContactAlerts.php, app-modules/contact/src/Filament/Widgets/ContactStats.php, app-modules/contact/src/Observers/ContactObserver.php, app-modules/report/src/Filament/Widgets/RefreshWidget.php, app-modules/report/src/Filament/Widgets/ServiceRequestStatusDistributionDonutChart.php, app-modules/report/src/Filament/Widgets/ServiceRequestsOverTimeLineChart.php, app-modules/report/src/Filament/Widgets/ServiceRequestsStats.php, app-modules/report/src/Filament/Widgets/TaskCumulativeCountLineChart.php, app-modules/report/src/Filament/Widgets/TaskStats.php, app/Filament/Widgets/ContactGrowthChart.php
- https://canyongbs.atlassian.net/browse/AIDAPP-589
> Ensure all usage of Cache::tags apply Redis "hash tags" to the tag
> No
> No
=> [AIDAPP-589]: Ensure all usage of Cache::tags apply Redis "hash tags" to the tag

app-modules/service-management/src/Jobs/ServiceMonitoringCheckJob.php, app-modules/service-management/tests/Jobs/ServiceMonitoringCheckJobTest.php
- https://canyongbs.atlassian.net/browse/AIDAPP-592
> ServiceMonitoringCheckJob fails if the provided URL is unresolvable
> No
> No
=> [AIDAPP-592]: ServiceMonitoringCheckJob fails if the provided URL is unresolvable

.github/workflows/ci.yml
- N/A
Fixes a bug in our GitHub CI process by making sure we checkout the branch properly and upgrades to the most recent version of the auto commit action.
No
No
=> [CHORE]: Make sure to fully checkout and upgrade stefanzweifel/git-auto-commit-action

app-modules/portal/routes/api.php, app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/IncidentController.php, app-modules/portal/tests/Unit/IncidentApiTest.php, portals/knowledge-management/src/Components/Loader.vue, portals/knowledge-management/src/Pages/Incidents.vue, portals/knowledge-management/src/portal.js
- https://canyongbs.atlassian.net/browse/AIDAPP-597
> Implement on page content for incident page
> No
> No
=> [AIDAPP-597]: Implement on page content for incident page

portals/knowledge-management/src/Pages/Incidents.vue
- https://canyongbs.atlassian.net/browse/AIDAPP-617
> Some users have reported that several information in the client portal incidents report are not displaying properly
> No
> No
=> Some users have reported that several information in the client portal incidents report are not displaying properly

_ide_helper_models.php, app-modules/inventory-management/src/Models/AssetCheckIn.php, app-modules/inventory-management/src/Models/AssetCheckOut.php, app-modules/portal/routes/api.php, app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/AssetManagementPortalController.php, portals/knowledge-management/src/Pages/Assets.vue, portals/knowledge-management/src/portal.js
- https://canyongbs.atlassian.net/browse/AIDAPP-614
> Show checked out and returned assets related to the contact record in the client portal
> No
> No
=> [AIDAPP-614]: Show checked out and returned assets related to the contact record in the client portal

resources/css/app.css, resources/views/vendor/cookie-consent/dialog.blade.php
- https://canyongbs.atlassian.net/browse/AIDAPP-619
Make some visual changes to GDPR banner.
No
No
=> [AIDAPP-619]: Enhance the display of the GDPR banner on the portal

_ide_helper_models.php, app-modules/engagement/database/factories/UnmatchedInboundCommunicationFactory.php, app-modules/engagement/database/migrations/2025_06_24_142144_create_unmatched_inbound_communications_table.php, app-modules/engagement/database/migrations/2025_06_24_153744_data_activate_unmatch_inbound_communication_feature.php, app-modules/engagement/src/Jobs/ProcessSesS3InboundEmail.php, app-modules/engagement/src/Jobs/UnmatchedInboundCommunicationsJob.php, app-modules/engagement/src/Models/UnmatchedInboundCommunication.php, app-modules/engagement/tests/Jobs/UnmatchInboundResponseTest.php, app/Console/Kernel.php, app/Features/UnMatchInboundCommunicationFeature.php
- https://canyongbs.atlassian.net/browse/AIDAPP-629
> Store all unmatched inbound emails and text messages
> No
> Yes, `UnMatchInboundCommunicationFeature`
=> [AIDAPP-629]: Store all unmatched inbound emails and text messages

app/Console/Kernel.php
- N/A
Fix issue where the `UnmatchedInboundCommunicationsJob` is not dispatched in the correct Tenant context.
No
No
=> [Bugfix]: Make sure UnmatchedInboundCommunicationsJob is dispatched in correct Tenant context

app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/CreateServiceRequestController.php, app-modules/service-management/src/Models/ServiceRequest.php
- N/A
Report Service request creation issues more verbosely and refresh the service request when it is created.
No
No
=> [Bugfix]: Add Checks and refresh for Service Request creation in portal

app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/CreateServiceRequestController.php, app-modules/service-management/src/Models/ServiceRequest.php
- N/A
Merge hotfix `0.68.3` back into `main`.
No
No
=> [Hotfix]: 0.68.3

.github/workflows/ci.yml, .gitignore, app-modules/in-app-communication/src/Actions/AddUserToConversation.php, app-modules/in-app-communication/src/Actions/CreateTwilioConversation.php, app-modules/in-app-communication/src/Filament/Pages/UserChat.php, app-modules/integration-twilio/src/DataTransferObjects/TwilioApiKey.php, app-modules/service-management/database/factories/ServiceRequestStatusFactory.php, app/Console/Commands/CreatePermissionMigration.php, app/PhpMd/CamelCasePropertyNameWithoutSettings.php, app/Providers/HealthServiceProvider.php, app/Support/HasAdvancedFilter.php, composer.json, composer.lock, phpmd.baseline.xml, phpmd.ruleset.xml, phpstan.neon.dist, tests/TestCase.php
- N/A
Set up PHPMD, resolve violations, and baseline any that are too risky to be worth fixing now.
No
No
=> [Chore]: Setup PHPMD

app-modules/in-app-communication/src/Events/ConversationMessageSent.php, app-modules/in-app-communication/src/Jobs/NotifyConversationParticipant.php, app-modules/in-app-communication/src/Jobs/NotifyConversationParticipants.php, app/Console/Commands/CreateTenant.php, app/Overrides/LaravelSqsExtended/SqsDiskConnector.php, app/Overrides/LaravelSqsExtended/SqsDiskJob.php, app/Overrides/LaravelSqsExtended/SqsDiskQueue.php, app/Providers/QueueServiceProvider.php, composer.json, composer.lock, config/app.php, config/queue.php, config/sentry.php, tests/Expectations.php
- https://canyongbs.atlassian.net/browse/AIDAPP-652
Solves issues with SQS large payloads by making sure we can restore the Tenant that their payload was stored into.
Also removes the trailing hash to the `release` we send to Sentry so that it just sends the semver tag for better functionality in Sentry logs.
No
No
=> [AIDAPP-652]: Implement performance and infrastructure improvements for audit record consistency

app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php, app/Filament/Widgets/ListServiceRequestTableWidgets.php
- https://canyongbs.atlassian.net/browse/AIDAPP-649
> Some users are experiencing issues where searching for a service request is not working as expected
> No
> No
=> [AIDAPP-649]: Some users are experiencing issues where searching for a service request is not working as expected

app-modules/service-management/database/migrations/2025_08_11_143616_add_is_reminders_enabled_in_service_request_types_table.php, app-modules/service-management/database/migrations/2025_08_11_143801_add_survey_and_reminder_fields_to_service_requests_table.php, app-modules/service-management/src/Filament/Resources/ServiceRequestResource.php, app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/CreateServiceRequestType.php, app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/EditServiceRequestType.php, app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/ViewServiceRequestType.php, app-modules/service-management/src/Jobs/SendClosedServiceRequestFeedbackReminders.php, app-modules/service-management/src/Models/ServiceRequest.php, app-modules/service-management/src/Models/ServiceRequestType.php, app-modules/service-management/src/Notifications/SendClosedServiceFeedbackNotification.php, app/Console/Kernel.php, app/Features/FeedbackReminderFeature.php, database/migrations/2025_08_11_144015_data_activate_feedback_reminder_feature.php
- https://canyongbs.atlassian.net/browse/AIDAPP-666
> Introduce service feedback reminder option
> No
> Yes. `FeedbackReminderFeature`
=> [AIDAPP-666]: Introduce service feedback reminder option

app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/ServiceRequestTypeEmailTemplatePage.php, app-modules/service-management/src/Notifications/Concerns/HandlesServiceRequestTemplateContent.php
- https://canyongbs.atlassian.net/browse/AIDAPP-687
> Add a merge value across all service request templates for contact name
> No
> No
=> [AIDAPP-687]: Add a merge value across all service request templates for contact name

portals/knowledge-management/src/Pages/CreateServiceRequest.vue, portals/knowledge-management/src/Pages/SelectServiceRequestType.vue
- https://canyongbs.atlassian.net/browse/AIDAPP-694
- Fix Spacing and Alignment issues with Service Requests form
- No
- No
=> [AIDAPP-694]:  Some users are reporting that forms are not remaining within the bounds of the page

app-modules/service-management/src/Models/Sla.php, app-modules/service-management/src/Notifications/ChangeRequestAwaitingApprovalNotification.php, app-modules/service-management/src/Notifications/SendClosedServiceFeedbackNotification.php, app-modules/service-management/src/Notifications/ServiceRequestAssigned.php, app-modules/service-management/src/Notifications/ServiceRequestClosed.php, app/Filament/Widgets/ServiceRequestDonutChart.php, app/Filament/Widgets/ServiceRequestLineChart.php, app/Filament/Widgets/ServiceRequestWidget.php, app/Models/Concerns/BelongsToEducatable.php, database/factories/Concerns/RandomizeState.php
- https://canyongbs.atlassian.net/browse/AIDAPP-#
> Solve lint issues
> Before: 929
> After: 907
> No.
> No.
=> Solve lint issues

app-modules/form/src/Http/Middleware/EnsureSubmissibleIsEmbeddableAndAuthorized.php, app-modules/portal/src/Http/Middleware/EnsureKnowledgeManagementPortalIsEmbeddableAndAuthorized.php
- N/A
Fixes an issue with widgets not loading correctly when embedded on the same domain as the app.
No
No
=> [Bugfix]: Check requesting URL headers if origin is missing
