app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/CreateServiceRequest.php
app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/EditServiceRequest.php
app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ViewServiceRequest.php
app-modules/service-management/tests/ServiceRequest/ViewServiceRequestTest.php

- https://canyongbs.atlassian.net/browse/AIDAPP-
>In Service request creation some label names (Close/Description to "Description " and Internal Service Request Details to "Internal Details") has been renamed and display of Description and Internal Details 50/50 display now. In Division dropdown Logged in user's team default division will be auto selected if user's team belongs to any division.

[AIDAPP-50] Enhance the labels used for Service Requests

---

resources/views/vendor/mail/html/header.blade.php

- https://canyongbs.atlassian.net/browse/AIDAPP-61
> Added the url() function in header.blade.php to fix default image not displaying in emails. 

[AIDAPP-61] Default logo for image in emails is broken

---

app-modules/portal/src/Filament/Pages/ManagePortalSettings.php
app-modules/service-management/src/Filament/Resources/ServiceRequestFormResource/Pages/EditServiceRequestForm.php
app-modules/survey/src/Filament/Resources/SurveyResource/Pages/EditSurvey.php

- https://canyongbs.atlassian.net/browse/AIDAPP-64
Fixes the display of the Knowledge Portal Embed code display. Does the same for Survey and Service Request Forms.
>

[AIDAPP-64]: Unable to embed knowledge portal

---

app/Multitenancy/Tasks/SwitchS3FilesystemTask.php
app/Multitenancy/Tasks/SwitchS3PublicFilesystemTask.php

- https://canyongbs.atlassian.net/browse/AIDAPP-82
Clears the Storage facade after we set the filesystem config so settings are not shared between Tenants.
>

[AIDAPP-82]: Forget the disks after setting config values

---

app-modules/integration-aws-ses-event-handling/src/Filament/Pages/ManageAmazonSesSettings.php
app-modules/notification/src/Notifications/Messages/MailMessage.php
app-modules/notification/tests/Features/NotificationFromNameTest.php
app-modules/notification/tests/Features/TestEmailSettingFromNameNotification.php
app/Filament/Resources/NotificationSettingResource/Forms/NotificationSettingForm.php
app/Filament/Resources/NotificationSettingResource/Pages/CreateNotificationSetting.php
app/Filament/Resources/NotificationSettingResource/Pages/EditNotificationSetting.php
app/Multitenancy/DataTransferObjects/TenantMailConfig.php
config/health.php
config/mail.php
database/migrations/2024_06_03_173514_add_from_column_to_notification_settings_table.php
database/migrations/2024_06_03_173540_data_activate_notification_settings_from_name_column.php
database/migrations/2024_06_03_183502_seed_manage_ses_settings_permission.php

- https://canyongbs.atlassian.net/browse/AIDAPP-83
> Adds same configuration that was implemented on AdvisingApp in order to allow admins to configure the email "from name" either globally or per Notification Setting.
> No

[AIDAPP-83]: Add configurability of email from name

---

app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/CreateKnowledgeBaseItem.php
app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/EditKnowledgeBaseItemMetadata.php

- https://canyongbs.atlassian.net/browse/AIDAPP-115
Fixes the Division select box during KB item create and edit to match the relationship type.
>

[AIDAPP-115]: Setting division when creating a knowledge article produces an error

---

app-modules/engagement/src/Actions/DeliverEngagements.php

- https://canyongbs.atlassian.net/browse/AIDAPP-122
> Delays the release of the DeliverEngagements job back to the queue to prevent `MaxAttemptsExceededException`
> No

[AIDAPP-122]: Fix DeliveryEngagements Job

---

app-modules/form/src/Actions/GenerateSubmissibleEmbedCode.php
app-modules/portal/src/Actions/GeneratePortalEmbedCode.php
app/Providers/AppServiceProvider.php

- https://canyongbs.atlassian.net/browse/AIDAPP-135
> Takes the same approach as was introduced in Advising App to append the commit hash as a query parameter to the portal script.
> No

[AIDAPP-135]: Add tag for dependencies to avoid caching of assets as they change from release to release

---

app/Http/Requests/Tenants/CreateTenantRequest.php

- https://canyongbs.atlassian.net/browse/AIDAPP-157
This removes `onlineSurveys` as a required field in `CreateTenantRequest`. As `onlineSurveys` is no longer an Addon in AidingApp and was removed on the Olympus side and in the Addon DTO here.
>

[AIDAPP-157]: Creation of AidingApp Tenant Failed

---

app-modules/portal/src/Filament/Pages/ManagePortalSettings.php

- https://canyongbs.atlassian.net/browse/AIDAPP-150
> Setting a favicon or logo should not be possible when KB is disabled

[AIDAPP-150]: Setting a favicon or logo should not be possible when KB is disabled

---

docker-compose.dev.yml
docker-compose.prod.yml
docker-compose.yml
docs/local-setup.md

- https://canyongbs.atlassian.net/browse/AIDAPP-171
The documentation has been updated to specify the version number of Docker and Docker Compose needed for the project. We have also removed the deprecated `version` parameter from all Docker Compose Yaml files.
>

[AIDAPP-171]: Update all docs to instruct users to update to the most recent version of Docker

---

app-modules/contact/src/Models/Contact.php
app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php
app-modules/service-management/tests/ServiceRequest/ListServiceRequestsTest.php

- https://canyongbs.atlassian.net/browse/AIDAPP-169
> Added filter by organization in List Service Request Page.
According to the screenshot below, the Service Request is filtered by the Organization.
> No
> No

[AIDAPP-169]: Introduce ability to filter by Organization within service requests

---

database/migrations/2024_07_10_085735_data_update_value_of_time_to_resolution_in_service_request.php

- https://canyongbs.atlassian.net/browse/AIDAPP-188
Fix bug caused by `diffInSeconds` call to non-object.
No
No

[AIDAPP-188]: Fix diffInSeconds bug

---

app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ViewServiceRequest.php

- https://canyongbs.atlassian.net/browse/AIDAPP-178
> Fixed the lock service request icon display on view service request page. 
> No
> No

[AIDAPP-178] Remove lock icon from service requests that are not in a closed state

---

docker/s6-overlay/scripts/fix-permissions

- https://canyongbs.atlassian.net/browse/AIDAPP-193
Fix error that is thrown during first time startup if `rr` is missing.
No.
No.

[AIDAPP-193]: Error is thrown due to rr file missing when setting up the project for the first time

---

app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseItemResource/Pages/ListKnowledgeBaseItems.php

- https://canyongbs.atlassian.net/browse/AIDAPP-195
> Change the knowledge management button label from 'Replicate' to 'Duplicate'
> No.
> No.

[AIDAPP-195]: Improve the label used to indicate copying or duplicating a knowledge base article

---

app-modules/service-management/src/Filament/Resources/ServiceRequestResource/RelationManagers/AssignedToRelationManager.php
app-modules/service-management/src/Filament/Resources/ServiceRequestResource/RelationManagers/ServiceRequestUpdatesRelationManager.php
app-modules/service-management/src/Filament/Resources/ServiceRequestUpdateResource/Pages/ViewServiceRequestUpdate.php
app-modules/service-management/src/Policies/ServiceRequestUpdatePolicy.php
app-modules/service-management/tests/ServiceRequest/EditServiceRequestTest.php
app-modules/service-management/tests/ServiceRequestUpdate/EditServiceRequestUpdateTest.php
app/Http/Controllers/SetAzureSsoSettingController.php

- https://canyongbs.atlassian.net/browse/AIDAPP-179
> When a service request reaches a closed state, the system should automatically disable the creation of new Updates and modifications to Service Request Assignments. Users should only be able to view the request details in a read-only mode.
> No
> No

[AIDAPP-179] Disable Updates and Service Request Assignments for service requests that are in a closed state to prevent modifications

---

docker/s6-overlay/scripts/laravel-octane

- https://canyongbs.atlassian.net/browse/AIDAPP-210
Fixes Octane to run as the `webuser` for better security and to prevent `git` dubious ownership.
No
No

[AIDAPP-210]: Generating a version tag for assets is failing

---

.env.example
docker-compose.dev.yml
docker/s6-overlay/scripts/startup-caching

- https://canyongbs.atlassian.net/browse/AIDAPP-203
Adds module caching during application startup.
Must wait to merge in until https://github.com/canyongbs/devops/pull/36 is merged into `main` and this repos submodule is updated to point to that new commit.
No
No

[AIDAPP-203]: Add module caching to startup-caching

---

resources/views/landlord.blade.php

- https://canyongbs.atlassian.net/browse/AIDAPP-218
> Old flowbite svg is still referenced on Landlord page - done
> No.
> No.
__________________________________________

[AIDAPP-218] : Old flowbite svg is still referenced on Landlord page

---

_ide_helper_models.php
app-modules/portal/database/migrations/2024_08_14_201456_activate__gdpr_banner_customization.php
app-modules/portal/src/Enums/GdprBannerButtonLabel.php
app-modules/portal/src/Filament/Pages/ManagePortalSettings.php
app-modules/portal/src/Settings/PortalSettings.php
app/Enums/FeatureFlag.php
app/Providers/AppServiceProvider.php
database/settings/2024_08_14_181705_add_gdrp_settings_to_portal_settings.php
package-lock.json
resources/views/vendor/cookie-consent/dialog.blade.php

- https://canyongbs.atlassian.net/browse/AIDAPP-151
Adds the ability to customize the GDPR Banner for the Portal.
Adds the Feature Flag for this in a new way I would like to propose. We will now place Feature Flags in this new `FeatureFlag` ENUM. This way they are in a central location and it is easier to track when we have left any behind.
They are actually truly registered in the Service Provider with this ENUM, that way once all Feature Flags are like this we no longer have to have a purge migration during cleanup. We would setup a task to purge all flags that are not currently registered.
When we cleanup a Feature Flag we would delete it from the ENUM and remove it's reference from everywhere in the app. Even the initial activate migration.
This also allows use to define an active …

[AIDAPP-151]: Introduce the ability to configure the text shown for the cookie banner.

---

app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalController.php

- https://canyongbs.atlassian.net/browse/AIDAPP-223
> Give default logo in client portal page.
> No.
> No.

[AIDAPP-223]: When no logo is set for the client portal, it should default to the product logo, but instead it displays a broken image.

---

.github/workflows/ci.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/update_yearly_copyright.yml

- https://canyongbs.atlassian.net/browse/AIDAPP-233
Updates all GitHub Action versions and locks some to a particular commit with a SHA.
No
No

[AIDAPP-233]: Update GitHub Action step versions

---

docker-compose.dev.yml

- https://canyongbs.atlassian.net/browse/AIDAPP-246
Adds needed configuration to work with changes to the `traefik` repo, allowing the app containers to communicate via subdomain.
No
No

[AIDAPP-246]: Modify local configuration to allow containers to reach each other via subdomain 

---

Dockerfile

- https://canyongbs.atlassian.net/browse/AIDAPP-204
Removes prod chmod of `rr` file that does not exist anymore.
No
No

[AIDAPP-204]: Remove chmod of non-existant rr

---

resources/views/vendor/cookie-consent/dialog.blade.php

- N/A
Removes reference to old FeatureFlag ENUM that was missed.
No
No

[Bugfix]: Remove reference to old FeatureFlag ENUM

---

docker-compose.yml

- https://canyongbs.atlassian.net/browse/AIDAPP-293
Resolves issues in our Docker Compose setup by removing duplicate `extra_hosts` entries that are no longer allowed in recent Docker version.
No
No

[AIDAPP-293]: Resolve issues in our Docker Compose setup from Docker Updates

---

resources/views/vendor/cookie-consent/dialog.blade.php

- https://canyongbs.atlassian.net/browse/AIDAPP-299
> When viewing the GDPR banner, the message is presented outside of the intended CSS container
> No
> No

[AIDAPP-299]: When viewing the GDPR banner, the message is presented outside of the intended CSS container

---

.config/psysh/psysh_history
.gitignore
app-modules/knowledge-base/database/factories/KnowledgeBaseCategoryFactory.php
app-modules/knowledge-base/database/migrations/2024_10_10_115843_add_slug_to_knowledge_base_categories_table.php
app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseCategoryResource/Pages/CreateKnowledgeBaseCategory.php
app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseCategoryResource/Pages/EditKnowledgeBaseCategory.php
app-modules/knowledge-base/src/Filament/Resources/KnowledgeBaseCategoryResource/Pages/ViewKnowledgeBaseCategory.php
app-modules/knowledge-base/src/Models/KnowledgeBaseCategory.php
app-modules/knowledge-base/tests/KnowledgeBaseCategory/RequestFactories/CreateKnowledgeBaseCategoryRequestFactory.php
app/Features/KnowledgeBaseCategorySlug.php
database/migrations/2024_10_10_142117_data_activate_feature_flag_knowledge_base_category_slug.php

- https://canyongbs.atlassian.net/browse/AIDAPP-303
> In the Knowledge Base Category, Added a Slug field with validation for unique, hyphenated, alphanumeric values only on create, edit, and view pages.
> No
> Yes. "KnowledgeBaseCategorySlug".

[AIDAPP-303]: Extend the model for knowledge base categories to have a slug value

---

app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/CreateServiceRequestController.php

- https://canyongbs.atlassian.net/browse/AIDAPP-277
> "New" label set when a service request created from the portal.
> No.
> No.

[AIDAPP-277]: Ensure a status is set to New when a service request is created in the portal

---

.config/psysh/psysh_history
app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php
app-modules/service-management/src/Policies/ServiceRequestPolicy.php
app-modules/service-management/tests/ServiceRequest/ListServiceRequestsTest.php
app-modules/service-management/tests/ServiceRequest/ViewServiceRequestTest.php

- https://canyongbs.atlassian.net/browse/AIDAPP-301
> Prevent users from viewing service requests of types that they are not managers or auditors of.
> No.
> No.

[AIDAPP-301] Prevent users from viewing service requests of types that they are not managers or auditors of

---

app-modules/portal/src/DataTransferObjects/KnowledgeBaseArticleData.php
app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalArticleController.php
portals/knowledge-management/src/Pages/ViewArticle.vue

- https://canyongbs.atlassian.net/browse/AIDAPP-309
After changing an article from public to internal, the article is still available via the link on the portal
No
No

[AIDAPP-309]: After changing an article from public to internal, the article is still available via the link on the portal

---

.env.example

When following the setup instructions, the sample admin is seeded without an email address, so it is impossible to sign in. I didn't realise that it was actually a blank value in the `.env.example`.
Advising doesn't use an env var here, so could be worth making this consistent in the future.

Add default DEV_SUPER_ADMIN_EMAIL to .env.example

---

_ide_helper_models.php
app-modules/portal/routes/api.php
app-modules/portal/src/DataTransferObjects/KnowledgeBaseArticleData.php
app-modules/portal/src/DataTransferObjects/KnowledgeBaseCategoryData.php
app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalArticleController.php
app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalCategoryController.php
app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/KnowledgeManagementPortalSearchController.php
app-modules/portal/src/Http/Routing/ArticleShowMissingHandler.php
app-modules/portal/src/Http/Routing/CategoryShowMissingHandler.php
app-modules/portal/src/Models/KnowledgeBaseArticleVote.php
app-modules/portal/src/Models/PortalGuest.php
package-lock.json
package.json
portals/knowledge-management/src/Components/Article.vue
portals/knowledge-management/src/Components/HelpCenter.vue
portals/knowledge-management/src/Components/SearchResults.vue
portals/knowledge-management/src/Pages/ViewArticle.vue
portals/knowledge-management/src/Pages/ViewCategory.vue
portals/knowledge-management/src/portal.js

- https://canyongbs.atlassian.net/browse/AIDAPP-353
Set up routing for Article categories based on slugs rather than ID, but it will still redirect to the correct slug URL if an ID URL is accessed for backward compatibility.
No
No

[AIDAPP-353]: Update routes to use category slugs for articles and categories with fall back

---

app-modules/portal/routes/api.php

- https://canyongbs.atlassian.net/browse/AIDAPP-356
Fixes a bug with routes once cached by changed to first class callables.
No
No

[AIDAPP-356]: Change to using first class callables

---

app/Console/Commands/ConnectOlympus.php

- https://canyongbs.atlassian.net/browse/OLYMPUS-196
When connecting, the protocol is forced as HTTPS when sending app data back to Olympus.
No
No

[OLYMPUS-196]: Ensure all requests between Olympus and the other application are done over HTTPS

---

app-modules/authorization/database/migrations/2024_12_30_200843_2024_12_30_142708_add_matching_property_to_azure_sso_settings.php
app-modules/authorization/database/migrations/2024_12_30_200951_data_activate_azure_matching_property_feature.php
app-modules/authorization/src/Enums/AzureMatchingProperty.php
app-modules/authorization/src/Enums/SocialiteProvider.php
app-modules/authorization/src/Exceptions/InvalidAzureMatchingProperty.php
app-modules/authorization/src/Filament/Pages/ManageAzureSsoSettings.php
app-modules/authorization/src/Http/Controllers/SocialiteController.php
app-modules/authorization/src/Settings/AzureSsoSettings.php
app/Features/AzureMatchingPropertyFeature.php

- https://canyongbs.atlassian.net/browse/AIDAPP-395
Adds the ability to configure which Azure User parameter the email for login is matched on.
No
Feature Flag: `AzureMatchingPropertyFeature`

[AIDAPP-395]: Introduce additional configuration in the SSO settings for Microsoft Azure AD

---

app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php
app-modules/service-management/tests/ServiceRequest/ListServiceRequestsTest.php

- https://canyongbs.atlassian.net/browse/AIDAPP-421
> By default, exclude closed service requests via a removable filter from dashboard and service request list views
> No.
> No.

[AIDAPP-421]: By default, exclude closed service requests via a removable filter from dashboard and service request list views

---

app/Filament/Widgets/ListServiceRequestTableWidgets.php

- https://canyongbs.atlassian.net/browse/AIDAPP-437
> Remove the service request title column field from the dashboard.
> No.
> No.

[AIDAPP-437]: Remove the service request title column field from the dashboard

---

app-modules/portal/src/Http/Controllers/KnowledgeManagementPortal/CreateServiceRequestController.php

- https://canyongbs.atlassian.net/browse/AIDAPP-446
> Tickets are failing to automatically assign the designated user when creating new service request from portal side.
> No
> No

[AIDAPP-446]: Tickets are failing to automatically assign the designated user on new ticket creation

---

app-modules/service-management/src/Filament/Resources/ServiceRequestResource/RelationManagers/ServiceRequestUpdatesRelationManager.php

- https://canyongbs.atlassian.net/browse/AIDAPP-447
Add an optional Change Status option to happen simultaneously when creating a service request update
No
No

[AIDAPP-447]: Add an optional Change Status option to happen simultaneously when creating a service request update

---

app-modules/authorization/tests/Feature/Filament/Resources/User/ListUsersTest.php
app/Filament/Resources/UserResource.php

- https://canyongbs.atlassian.net/browse/AIDAPP-458
> Introduce the ability to filter the user list by team
> No
> No

[AIDAPP-458]: Introduce the ability to filter the user list by team

---

app-modules/division/database/factories/DivisionFactory.php
app-modules/division/database/migrations/2025_02_19_171906_remove_header_footer_coloumns_from_divisions_table.php
app-modules/division/database/seeders/DivisionSeeder.php
app-modules/division/src/Filament/Resources/DivisionResource/Pages/CreateDivision.php
app-modules/division/src/Filament/Resources/DivisionResource/Pages/EditDivision.php
app-modules/division/src/Filament/Resources/DivisionResource/Pages/ViewDivision.php
app-modules/division/src/Models/Division.php

- https://canyongbs.atlassian.net/browse/AIDAPP-456
Remove header and footer fields from Division pages, related files, and database.
No
No

[AIDAPP-456]: Remove obsolete header and footer configuration options for Division configuration

---

app/Filament/Resources/UserResource.php
app/Filament/Resources/UserResource/Actions/AssignTeamBulkAction.php
app/Models/User.php

- https://canyongbs.atlassian.net/browse/AIDAPP-460
>  Introduce the ability to assign teams to users in bulk to improve access control management.
> No.
> No.

[AIDAPP-460]: Introduce the ability to assign teams to users in bulk to improve access control management

---

app-modules/division/database/factories/DivisionFactory.php
app-modules/division/database/migrations/2025_02_19_125148_add_column_is_default_in_divisions_table.php
app-modules/division/src/Filament/Resources/DivisionResource/Pages/CreateDivision.php
app-modules/division/src/Filament/Resources/DivisionResource/Pages/EditDivision.php
app-modules/division/src/Filament/Resources/DivisionResource/Pages/ListDivisions.php
app-modules/division/src/Filament/Resources/DivisionResource/Pages/ViewDivision.php
app-modules/division/src/Models/Division.php
app-modules/division/src/Observers/DivisionObserver.php
app-modules/team/src/Filament/Resources/TeamResource/Pages/CreateTeam.php
app-modules/team/src/Filament/Resources/TeamResource/Pages/EditTeam.php
app-modules/team/src/Filament/Resources/TeamResource/Pages/ViewTeam.php
app/Features/DivisionIsDefault.php
database/migrations/2025_02_19_125556_data_activate_division_is_default_feature_flag.php

- https://canyongbs.atlassian.net/browse/AIDAPP-455
>Add 'is_default' feature to Division model and related components
> No.
> Yes.
> DivisionIsDefault

[AIDAPP-455]: Improve the user relationship between teams and divisions

---

app-modules/service-management/tests/ServiceRequestStatus/CreateServiceRequestStatusTest.php

- https://canyongbs.atlassian.net/browse/AIDAPP-482
The system creates an open / info record so that needs to be purged before running the test or we will get flaky issues during the random time it tries to create a record similar to that.
No
No

[AIDAPP-482]: Fix flaky test CreateServiceRequestTest

---

portals/knowledge-management/src/App.vue
portals/knowledge-management/vite.config.js
widgets/service-request-feedback-form/src/App.vue
widgets/service-request-feedback-form/vite.config.js
widgets/service-request-form/src/App.vue
widgets/service-request-form/vite.config.js

- https://canyongbs.atlassian.net/browse/AIDAPP-485
Fixes the issue in a non-cache busting way so that they output as `style.css` like they used to.
No
No

[AIDAPP-485]: Change the vite config to name the stylesheets style.css

---

config/health.php

- https://canyongbs.atlassian.net/browse/AIDAPP-502
Disables the Spatie Health checks from sending emails as we get these notices in Olympus now.
No
No

[AIDAPP-502]: Disable health check process from sending emails

---

app-modules/engagement/src/Notifications/EngagementNotification.php
app/Models/User.php

- https://canyongbs.atlassian.net/browse/AIDAPP-530
> Fixed: Engagements sent to contacts are not using the correct communication settings configuration attached to the division.
> No.
> No.

[AIDAPP-530]: Engagements sent to contacts are not using the correct communication settings configuration attached to the division.

---

composer.json
composer.lock

- https://canyongbs.atlassian.net/browse/AIDAPP-536
> Update Laravel Octane to version 2.8.3
> No
> No

[AIDAPP-536]: Update Laravel Octane to version 2.8.3

---

composer.lock

Signed-off-by: Dan Harrin <dan.harrin@canyongbs.com>
- https://canyongbs.atlassian.net/browse/OLYMPUS-441
Updates package
No
No

[OLYMPUS-441]: Tiptap merge tags type ahead is currently limited to only 5 items and typeahead search does not seem to be working

---

.github/workflows/ci.yml
Dockerfile
app-modules/service-management/tests/ServiceRequest/CreateServiceRequestTest.php
phpstan-ci.neon

- https://canyongbs.atlassian.net/browse/AIDAPP-538
Adds caching to the CI testing to speed up tests.
Also optimizing CI running to be much more efficient and resolves issues with debug tools loading in all environments.
No
No

[AIDAPP-538]: Apply Filament and Laravel auto discovery caching during CI linting and CI testing

---

composer.json
composer.lock

- https://canyongbs.atlassian.net/browse/AIDAPP-549
Update canyongbs/filament-tiptap-editor to version 1.2.3
No
No

[AIDAPP-549]: Update canyongbs/filament-tiptap-editor to version 1.2.3

---

app-modules/portal/routes/web.php
portals/knowledge-management/src/Components/Header.vue
portals/knowledge-management/src/portal.js

- https://canyongbs.atlassian.net/browse/AIDAPP-560
Remove the Knowledge Base menu page placeholder in the portal
No
No

[AIDAPP-560]: Remove the Knowledge Base menu page placeholder in the portal

---

portals/knowledge-management/src/App.vue
portals/knowledge-management/src/Components/Header.vue
portals/knowledge-management/src/portal.js

- https://canyongbs.atlassian.net/browse/AIDAPP-561
Just like service, incidents in the menu navigation should only show up if you are logged in
No
No

[AIDAPP-561]: Just like service, incidents in the menu navigation should only show up if you are logged in

---

app/Console/Kernel.php

- https://canyongbs.atlassian.net/browse/AIDAPP-570
Resolve an issue with the dispatching of the `ServiceMonitoringJob`'s during scheduler run.
No
No

[AIDAPP-570]: Error for too few arguments being passed to ServiceMonitoringJob

---

composer.lock

- https://canyongbs.atlassian.net/browse/AIDAPP-576
Update `league/commonmark` to [v2.7.0](https://github.com/thephpleague/commonmark/releases/tag/2.7.0)
No
No

[AIDAPP-576]: Resolve the security issue tracked under CVE-2025-46734

---

portals/knowledge-management/src/Components/Header.vue
portals/knowledge-management/src/portal.js

- https://canyongbs.atlassian.net/browse/AIDAPP-571
> Show new navigation option 'Status' on portal navigation only if user is logged in.
> No
> No

[AIDAPP-571]: Implement a new portal navigation page for status

---

_ide_helper_models.php
app-modules/service-management/database/factories/ServiceRequestTypeEmailTemplateFactory.php
app-modules/service-management/database/migrations/2025_05_09_113514_add_customers_survey_response_fields_in_service_request_types_table.php
app-modules/service-management/database/migrations/2025_05_12_101058_tmp_data_seed_for_survey_response_in_service_request_type_email_templates.php
app-modules/service-management/resources/views/blocks/previews/take-survey-link.blade.php
app-modules/service-management/resources/views/blocks/rendered/take-survey-link.blade.php
app-modules/service-management/resources/views/filament/resources/service-request-type-resource/pages/edit-service-request-type-notifications/matrix.blade.php
app-modules/service-management/src/Actions/GenerateServiceRequestTypeEmailTemplateContent.php
app-modules/service-management/src/Filament/Blocks/SurveyResponseEmailTemplateTakeSurveyButtonBlock.php
app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/EditServiceRequestTypeNotifications.php
app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/ServiceRequestTypeEmailTemplatePage.php
app-modules/service-management/src/Models/ServiceRequestType.php
app-modules/service-management/src/Notifications/Concerns/HandlesServiceRequestTemplateContent.php
app-modules/service-management/src/Notifications/SendClosedServiceFeedbackNotification.php
app-modules/service-management/src/Observers/ServiceRequestObserver.php
app-modules/service-management/src/Providers/ServiceManagementServiceProvider.php
app-modules/service-management/tests/ServiceRequest/EditServiceRequestTest.php
app-modules/service-management/tests/ServiceRequestType/ServiceRequestTypeEmailTemplatePageTest.php
app/Features/SurveyResponseTemplate.php
database/migrations/2025_05_13_073325_data_activate_feature_flag_survey_response_template.php

- https://canyongbs.atlassian.net/browse/AIDAPP-578
> Add survey response email functionality and UI components
- Introduced migration to add 'is_customers_survey_response_email_enabled' field to service_request_types table.
- Created new Blade components for survey response link previews and rendered views.
- Updated service request type notifications to include survey response options.
- Implemented survey response email template block for Filament.
- Enhanced service request observer to handle survey response notifications.
> No
> Yes. Feature flag: `SurveyResponseTemplate`
Temporary data migration:
`app-modules/service-management/database/migrations/2025_05_12_101058_tmp_data_seed_for_survey_response_in_service_request_type_email_templates.php` …

[AIDAPP-578]: Populate the email templates for CSAT and NPS survey service request email notifications including the current messaging that is used

---

app-modules/service-management/src/Jobs/ServiceMonitoringCheckJob.php

- https://canyongbs.atlassian.net/browse/AIDAPP-582
> Fixed: ServiceMonitoringCheckJob fails and throws an error if it's target requires more than 5 redirects.
> No.
> No.

[AIDAPP-582]: ServiceMonitoringCheckJob fails and throws an error if it's target requires more than 5 redirects

---

app-modules/portal/database/migrations/2025_06_11_103210_add_page_title_in_portal_settings.php
app-modules/portal/src/Actions/GeneratePortalEmbedCode.php
app-modules/portal/src/Filament/Pages/ManagePortalSettings.php
app-modules/portal/src/Livewire/RenderKnowledgeManagementPortal.php
app-modules/portal/src/Settings/PortalSettings.php
app/Features/PortalPageTitle.php
database/migrations/2025_06_11_132144_data_activate_portal_page_title_feature_flag.php
portals/knowledge-management/src/App.vue

- https://canyongbs.atlassian.net/browse/AIDAPP-613
> Introduce the ability to configure the page title in the client portal.
> No.
> Yes
> PortalPageTitle

[AIDAPP-613]: Introduce the ability to configure the page title in the client portal

---

portals/knowledge-management/src/Pages/ViewArticle.vue

- https://canyongbs.atlassian.net/browse/AIDAPP-620
Change background color of the 'Was this content helpful?' container to be white.
No
No

[AIDAPP-620]: Improve accessibility by changing the background color to white, enhancing contrast for the 'Was this content helpful?' container

---

app-modules/authorization/src/Http/Controllers/SocialiteController.php
app-modules/authorization/tests/Feature/Filament/Resources/UserResources/Pages/EditUserTest.php
composer.lock

- N/A
Fix an issue where Azure login logs an error that is not needed if they don't have a profile image.
No
No

[Bugfix]: Users not having profile images causes Azure to throw error to Sentry unnecessarily

---

Dockerfile

- N/A
Update Roadrunner binary to `2025.1.2`.
No
No

Update roadrunner to 2025.1.2

---

app/Http/Controllers/Tenants/CreateTenantController.php
app/Http/Requests/Tenants/CreateTenantRequest.php

- https://canyongbs.atlassian.net/browse/AIDAPP-657
Update the Olympus API Tenant creation process to no longer require the name of the Tenant be passed and now instead use the domain provided as the name of the Tenant and the key for the folder names in storage.
No
No

[AIDAPP-657]: Update Olympus API tenant creation to work without a name passed

---

app-modules/project/src/Filament/Resources/ProjectResource/Pages/ManageFiles.php

- https://canyongbs.atlassian.net/browse/AIDAPP-676
- Add `Retention Date` to Projects/Files table.
- Edit Column order
- Add date formatting on Created Date
- No
- No

[AIDAPP-676]: Enhance the display of files in a project by including a column for Retention Date

---

composer.lock

- https://canyongbs.atlassian.net/browse/AIDAPP-685
Updates `phpoffice/phpspreadsheet` to resolve CVE.
No
No

[AIDAPP-685]: Resolve the security issue tracked under CVE-2025-54370

---

Dockerfile
composer.json
composer.lock

- https://canyongbs.atlassian.net/browse/AIDAPP-674
- https://canyongbs.atlassian.net/browse/AIDAPP-684
Resolve security vulnerability CVE-2025-54801 & CVE-2025-9288 by upgrading `ysfkaya/filament-phone-input` and `roadrunner`.
No
No

[AIDAPP-674]: Resolve the security issue tracked under CVE-2025-54801 & [AIDAPP-684]: Resolve the security issue tracked under CVE-2025-9288

---

app-modules/service-management/src/Actions/ResetMonitoringAction.php
app-modules/service-management/src/Filament/Actions/ResetAction.php
app-modules/service-management/src/Filament/Resources/ServiceMonitoringResource/Pages/EditServiceMonitoring.php
app-modules/service-management/src/Filament/Resources/ServiceMonitoringResource/Pages/ViewServiceMonitoring.php
app-modules/service-management/tests/Tenant/Filament/ServiceMonitoring/Pages/ViewServiceMonitoringTest.php

- https://canyongbs.atlassian.net/browse/AIDAPP-696
- Create a custom action for Reseting Monitoring (soft deleting the history)
- Add the button to header actions on View / Edit pages.
- No
- No

[AIDAPP-696]: Introduce a button at the top of the page for service monitoring to reset monitoring

---

app-modules/form/src/Actions/GenerateSubmissibleEmbedCode.php
app-modules/form/src/Http/Middleware/EnsureSubmissibleIsEmbeddableAndAuthorized.php
app-modules/portal/src/Http/Middleware/EnsureKnowledgeManagementPortalIsEmbeddableAndAuthorized.php
app-modules/service-management/routes/api.php

- https://canyongbs.atlassian.net/browse/AIDAPP-698
Changes the authorized domains check to check the `origin` header instead of the insecure `referer` header.
Also updates `devops` submodule.
Also sets the form embed main URL to not be signed to prevent issues in the future if our key is rotated.
No
No

[AIDAPP-698]: Change embed authorized domain checks to check origin header, NOT referer

---

app-modules/service-management/tests/Tenant/Notifications/NotifyServiceRequestUsersTest.php

- https://canyongbs.atlassian.net/browse/AIDAPP-635
- When the test would run, sometimes (1 in every 400 times the test would run) the user order would be incorrect when runing the test. So I changed the tests to only care about the specific user instead of the order of the user.
- No
- No

[AIDAPP-635]: Improve unit testing for service request creation
